- README.md
- docs/index.rst
- manage.py
- settings/common.py
- settings/prod.py
- settings/testing.py
- Code Climate integration added
- Secret key now an environment variable
- Skipping some lines for code-checks
> Minor updates to the doc and config files

- .gitignore
- README.md
- settings/dev.sample.py
Now, there is a file `dev.sample.py` which users have to to rename to `dev.py` and then change configs. This will avoid pushing of hard coded values in `dev.py`.
> Development flow modified

- README.md
> Updated README added

- apps/accounts/models.py
- apps/challenges/models.py
- apps/hosts/models.py
- apps/teams/models.py
- evalai/urls.py
- requirements/common.txt
- settings/common.py
This pr updates the current code base, so that run server can be properly run. It comments out some import to resolve circular imports.
> Challenges cyclic import problem fix

- README.md
- frontend/gulpfile.js
Added dev task for development and connect task for server.
> Added dev specific Gulp task

- requirements/common.txt
- settings/common.py
> Add django-cors package to handle CORS.

- apps/challenges/serializers.py
- apps/teams/serializers.py
- apps/teams/urls.py
- apps/teams/views.py
- evalai/urls.py
- settings/common.py
> Team: Add Get api to list all teams for a particular challenge.

- frontend/index.html
- frontend/src/css/main.scss
- frontend/src/css/modules/auth.scss
- frontend/src/css/modules/base.scss
- frontend/src/css/modules/landing.scss
- frontend/src/css/modules/variables.scss
- frontend/src/js/app.js
- frontend/src/js/controllers/authCtrl.js
- frontend/src/js/controllers/mainCtrl.js
- frontend/src/js/route-config/route-config.js
- frontend/src/js/services/services.js
- frontend/src/views/web/auth.html
- frontend/src/views/web/login.html
- frontend/src/views/web/partials/dyn-header.html
- frontend/src/views/web/partials/sim-header.html
Added UI for login page and service for API calls
> login page UI

- apps/accounts/models.py
New fields are created_at and modified_at.
Issue #86
> Accounts: Rename created and modified fields of TimeStampedModel.

- apps/base/admin.py
- apps/base/apps.py
- apps/base/models.py
- apps/base/tests.py
- apps/base/views.py
- settings/common.py
> Apps: Add base app.

- apps/teams/views.py
This commit is actually a part of the create new team api.
Issue #34
> Teams: Add status when creating a new team.

- apps/teams/urls.py
> Team: Add url name for team apis.

- frontend/src/css/modules/auth.scss
- frontend/src/css/modules/base.scss
- frontend/src/css/modules/variables.scss
- frontend/src/js/app.js
- frontend/src/js/controllers/authCtrl.js
- frontend/src/js/route-config/route-config.js
- frontend/src/js/services/services.js
- frontend/src/views/web/auth.html
- frontend/src/views/web/login.html
- frontend/src/views/web/partials/dyn-header.html
- frontend/src/views/web/signup.html
> Sign Up page with API integration

- apps/hosts/serializers.py
- apps/hosts/views.py
> Hosts: Add create a new challenge host team api.

- apps/hosts/urls.py
- apps/hosts/views.py
> Hosts: Add get particular challenge host team api.

- apps/hosts/views.py
> Hosts: Add update particular challenge host team api.

- frontend/src/js/app.js
- frontend/src/js/controllers/authCtrl.js
- frontend/src/js/controllers/dashCtrl.js
- frontend/src/js/route-config/route-config.js
- frontend/src/js/services/services.js
- frontend/src/views/web/dashboard.html
- frontend/src/views/web/login.html
@deshraj :please check this PR.
> Login page with API implementation

- apps/accounts/models.py
- apps/base/models.py
- apps/challenges/models.py
- apps/hosts/models.py
- apps/participants/models.py
- apps/teams/models.py
This commit also updated the corresponding import statements.
Earlier this model was present in accounts app.
Issue #67
> Move TimeStampedModel to base app.

- frontend/app.scripts.json
- frontend/bower.json
- frontend/index.html
- frontend/src/js/controllers/authCtrl.js
- frontend/src/js/directives/directives.js
- frontend/src/js/route-config/route-config.js
- frontend/src/js/services/services.js
- frontend/src/views/web/dashboard.html
- frontend/src/views/web/login.html
- frontend/src/views/web/partials/dyn-header.html
User can redirect to dashboard after authentication otherwise redirect to login page.
> Added restrictions for auth routes

- apps/challenges/serializers.py
- apps/challenges/urls.py
- apps/challenges/views.py
> Challenges: Add api to get all challenges.

- apps/challenges/serializers.py
- apps/challenges/views.py
> Challenges: Add api to create a new challenge.

- apps/challenges/urls.py
- apps/challenges/views.py
> Challenges: Add API to get detail about a particular challenge.

- apps/challenges/views.py
> Challenges: Add API to update a particular challenge.

- apps/challenges/views.py
> Challenges: Add API to delete a particular challenge.

- apps/teams/serializers.py
- apps/teams/views.py
> Team: Rewrite TeamSerializer to contain context logic.

- frontend/src/js/controllers/authCtrl.js
- frontend/src/js/controllers/dashCtrl.js
- frontend/src/js/controllers/mainCtrl.js
- frontend/src/js/controllers/webCtrl.js
- frontend/src/js/route-config/route-config.js
- frontend/src/views/web/dashboard.html
- frontend/src/views/web/partials/dyn-header.html
- frontend/src/views/web/web.html
@deshraj : Have a look please!
> Added dashboard setup and improved auth

- apps/base/admin.py
#68 solved. @deshraj @TroJan Please review the PR.
> ModelAdmin class in base app to exclude created and modified fields.

- requirements.txt
- requirements/dev.txt
- Removes the duplicate requirements file
- Adds django rest swagger to requirements
> Added django-rest-swagger in requirements 

- frontend/src/views/web/dashboard.html
> removed minor bugs

- apps/hosts/views.py
> Hosts: Add support for query parameter status in challenge host get api.

- apps/hosts/serializers.py
> Hosts: Update ChallengeHost Serializer to return username instead of user id

- apps/hosts/urls.py
- apps/hosts/views.py
This api is a part of the flow to create a challenge api.
It firsts create a new challenge host team and then uses this
to create a new challenge host with status as Self and permissions
as Admin.
Issue #155
> Hosts: Add create challenge host and team api.

- frontend/src/css/modules/base.scss
> Chrome autofill transparent background

- frontend/src/views/web/login.html
- frontend/src/views/web/signup.html
Just added autofocus attribute to input field. Please have a look.
> Added autofocus to input fields

- tests/unit/hosts/test_views.py
> Tests: Add complete test case for challange host team model.

- frontend/app.scripts.json
- frontend/bower.json
- frontend/src/js/app.js
- frontend/src/views/web/landing.html
fixed  #84 .
@aka-jain  thanks a lot for the help.
> fixed scrolling

- tests/unit/hosts/test_views.py
> Tests: Add complete test case for challange host model.

- tests/unit/hosts/test_views.py
> Tests: Add test case for create challenge host and team flow.

- frontend/src/views/web/login.html
@deshraj : Merge this PR please.
> Reset position of Login Error Message

- tests/unit/challenges/test_views.py
> Test: Add test for challenge model.

- settings/prod.py
#146 solved. @deshraj Please review the PR.
> SMTP server working for sending mails.

- apps/participants/admin.py
#69  #71 Solved. @deshraj @TroJan please review the PR.
> Team app Modeladmin removed and added to Participants app.

- evalai/urls.py
- requirements/dev.txt
- settings/common.py
- settings/dev.sample.py
#193 Solved. @deshraj Please review the PR.
> Integrated django-spaghetti-and-meatballs to visualize database schema.

- frontend/src/css/modules/base.scss
- frontend/src/css/modules/footer.scss
- frontend/src/css/modules/variables.scss
- frontend/src/js/controllers/authCtrl.js
- frontend/src/js/route-config/route-config.js
- frontend/src/views/web/landing.html
- frontend/src/views/web/partials/footer.html
Added timout of 7 days to token and fixed some minor footer issues.
@deshraj have a look please!
> Added token expire timeout

- requirements/dev.txt
- settings/common.py
> added token expiration

- apps/participants/views.py
> Participants: Create Participant object when saving Participant Team object

- settings/common.py
A very basic logging configuration. Right now logging to files(log rotation also) is not added.
> settings: Setup logging for projects.

- apps/participants/serializers.py
- apps/participants/urls.py
- apps/participants/views.py
- tests/unit/participants/test_views.py
> Participants: Add api to invite a participant to join Participant team.

- apps/participants/serializers.py
- tests/unit/participants/test_views.py
> Participant: Add username in response of participant_team_list view.

- frontend/gulpfile.js
- frontend/index.html
- frontend/src/css/main.scss
- frontend/src/css/modules/base.scss
- frontend/src/css/modules/teams.scss
- frontend/src/css/modules/variables.scss
- frontend/src/js/controllers/teamsCtrl.js
- frontend/src/js/filters/filters.js
- frontend/src/js/route-config/route-config.js
- frontend/src/views/web/challenge-page.html
- frontend/src/views/web/partials/sidebar.html
- frontend/src/views/web/partials/sim-header.html
- frontend/src/views/web/teams.html
- settings/common.py
Changes Page size for pagination from 100 to 10. 
Added Team Creation/Selection page.
Solved Token expiration related bugs.
Add base for Challenge Page.
@deshraj Have a look please.
> Added team page, solved expire token time

- frontend/src/css/modules/teams.scss
> added dark gray radio button

- apps/challenges/permissions.py
- apps/challenges/views.py
#174 solved. @deshraj @TroJan Please review the PR.
> Set object level permissions to update/delete a challenge.

- evalai/urls.py
#247 solved. @deshraj Please review the PR.
> DrfDocs available on development server only.

- frontend/src/js/controllers/authCtrl.js
- frontend/src/views/web/auth.html
- frontend/src/views/web/login.html
@deshraj : Done with some changes
1. Removed autocomplete
2. Empty field after getting switched between views for better UX.
Have a look please!
> Removed auto complete with improved version of login/signup form

- frontend/src/js/controllers/authCtrl.js
- frontend/src/js/controllers/dashCtrl.js
- frontend/src/js/controllers/mainCtrl.js
- frontend/src/js/route-config/route-config.js
@deshraj : Added token validation based on API response. Please review it.
> Token validation

- apps/participants/serializers.py
#256 is solved. @TroJan is this okay ?
> Invite user to participant team api should be idempotent.

- evalai/urls.py
#277 solved. @deshraj  can you review ?
> Make Browsable API endpoint to be served in development environment only

- apps/challenges/views.py
- tests/unit/challenges/test_views.py
> Challenge: Add check to prevent mapping participant team to challenge more than once

- apps/challenges/serializers.py
- apps/challenges/urls.py
- apps/challenges/views.py
- tests/unit/challenges/test_views.py
> Challenge: Add api to fetch list of test environments.

- apps/challenges/serializers.py
- apps/challenges/views.py
- tests/unit/challenges/test_views.py
> Challenge: Add api to create a test environment.

- apps/challenges/urls.py
- apps/challenges/views.py
- tests/unit/challenges/test_views.py
> Challenge: Add api to get a particular test environment.

- apps/challenges/views.py
- tests/unit/challenges/test_views.py
> Challenge: Add api to update test environment.

- apps/challenges/views.py
- tests/unit/challenges/test_views.py
> Challenge: Add api to delete a particular test environment.

- README.md
> Updated node version and ruby dependency.

- evalai/urls.py
- evalai/views.py
- frontend/src/css/main.scss
- frontend/src/css/modules/error_500.scss
- frontend/src/views/web/error-pages/error-500.html
- frontend/src/views/web/error/404.html
- frontend/src/views/web/error/500.html
- settings/common.py
- tests/unit/evalai/test_views.py
#280 fixed. @deshraj Please review the PR.
> Custom Error Pages Added.

- apps/hosts/urls.py
- apps/hosts/views.py
- tests/unit/hosts/test_views.py
#338 solved. @deshraj Please review the PR.
> API endpoint for deleting a User from a Host Team.

- apps/participants/urls.py
- apps/participants/views.py
- tests/unit/participants/test_views.py
#336 solved. @deshraj Please review the PR.
> API for deleting a user from a Participant Team.

- apps/hosts/serializers.py
- tests/unit/challenges/test_views.py
- tests/unit/hosts/test_views.py
- tests/unit/participants/test_views.py
> Change `created_by` field from integer to username in `api/hosts/challenge_host_team/` API endpoint

- settings/dev.sample.py
> inserting PASSWORD in database

- requirements/common.txt
- requirements/prod.txt
- settings/dev.sample.py
- settings/test.py
#363 solved. @deshraj Please review the PR.
> django cache backend for the development environment.

- requirements/common.txt
- requirements/prod.txt
#368 solved. @deshraj Please review the PR.
> Moved uWSGI to prod. requirements file

- tests/unit/participants/test_urls.py
> Test urls for participants

- apps/accounts/admin.py
- apps/accounts/views.py
> Landscape Code quality increased for Accounts App.

- apps/base/views.py
> Landscape Code quality increased for Base App.

- apps/analytics/admin.py
- apps/analytics/models.py
- apps/analytics/urls.py
- apps/analytics/views.py
#390 Solved for Analytics app.
> Landscape Code quality increased for Analytics App.

- apps/challenges/models.py
- apps/challenges/permissions.py
- apps/challenges/views.py
#390 solved for challenges app.
> Landscape Code quality increased for Challenges App.

- apps/hosts/views.py
> Hosts: Unused imports removed from hosts app.

- apps/web/admin.py
- apps/web/models.py
> Web: Unused imports removed from web app.

- apps/jobs/admin.py
- apps/jobs/urls.py
- apps/jobs/views.py
>  Jobs: Unused imports removed from jobs app.

- evalai/urls.py
> Evalai : Unused imports removed from evalai

- settings/common.py
> Settings: Unused imports removed from settings

- tests/unit/accounts/test_urls.py
- tests/unit/challenges/test_models.py
- tests/unit/challenges/test_views.py
- tests/unit/evalai/test_views.py
- tests/unit/hosts/test_urls.py
- tests/unit/participants/test_urls.py
#390 solved for all the tests.
> Tests :Unused Imports removed from all tests.

- .landscape.yml
- .pylintrc
- setup.cfg
#390 solved. @deshraj Please review the PR.
> Fixes Landscape configuration.

- frontend/src/css/modules/web.scss
#374 solved. @aka-jain Please review the PR. Here are the screenshots.
> Footer: modified distance of the footer from the top of the screen.

- apps/challenges/serializers.py
- tests/unit/challenges/test_views.py
> Fix: Remove test_annotations field from ChallengePhase Serializer(#388)

- frontend/src/css/modules/header.scss
- frontend/src/views/web/partials/sim-header.html
Fix for Issue #250 
@aka-jain : Please review
> Fix: dashboard header issue on small screen devices(<480px)

- apps/jobs/urls.py
- apps/jobs/views.py
- tests/unit/jobs/test_views.py
#421 solved. @deshraj Please review the PR.
> API endpoint to get all the submissions made by user for a challenge phase.

- frontend/src/css/modules/variables.scss
#433 solved. @aka-jain Please review the PR.
> Updated variable.scss file for new UI

- apps/challenges/views.py
basically to increase code quality
> Challenge: Replace pagination code from utility function paginated_queryset

- frontend/src/js/controllers/challengeHostTeamsCtrl.js
> reset function added

- frontend/src/js/controllers/teamsCtrl.js
- frontend/src/views/web/teams.html
> input field cleared

- frontend/new-ui-components.html
#432 . @aka-jain Please review the PR.
> Added New Design to Host button.

- frontend/src/js/controllers/authCtrl.js
- frontend/src/js/route-config/route-config.js
- frontend/src/views/web/reset-password-confirm.html
this is regarding issue #118 
@aka-jain @deshraj : Please review
> Frontend(auth): Add forgot password module

- apps/participants/views.py
please check if its fine
issue #444
> changed to paginated_queryset

- frontend/src/css/modules/profile.scss
I've added a fixed position to it if any changes please suggest @aka-jain
> Fix: Profile Section is not fixed when scrolled(#439)

- apps/hosts/views.py
@deshraj @TroJan Please review the PR.
> changed to paginated_queryset in hosts app

- apps/challenges/urls.py
- apps/challenges/views.py
- tests/unit/challenges/test_urls.py
- tests/unit/challenges/test_views.py
Now get_all_challenge accpets either of ALL, FUTURE, PAST or PRESENT
as url arguments to return corresponding challenges.
Issue #457
> Challenge: Add support to get all challenge in get_all_challenge api.

- apps/participants/views.py
- tests/unit/participants/test_views.py
> Fixes #471: Participant teams not showing up.

- frontend/src/js/controllers/authCtrl.js
- frontend/src/views/web/login.html
- frontend/src/views/web/signup.html
> Frontend: Form Validations on Client Side.

- frontend/src/js/controllers/authCtrl.js
- frontend/src/js/route-config/route-config.js
- frontend/src/js/services/services.js
- frontend/src/views/web/verify-email.html
Now email verification link can be verified on client side.
Additional change: code quality improved in services.js
@deshraj : Please review
> Frontend(auth): Add email verification feature on client side

- frontend/src/js/controllers/teamsCtrl.js
@aka-jain #461 resolved, Please review!
> Fix: Correct Pagination Count in Team Page (#461)

- apps/challenges/views.py
- tests/unit/challenges/test_views.py
#485 solved. @deshraj Please review the PR.
> Added a check in Endpoint to check if challenge is active or not.

- frontend/src/js/controllers/authCtrl.js
- frontend/src/js/controllers/changePwdCtrl.js
- frontend/src/js/services/validation-services.js
- frontend/src/views/web/reset-password-confirm.html
Solution for issue #483
@aka-jain : Please review
> Frontend(service): Add client side validation service

- apps/participants/utils.py
Creates a new function which returns participant team ids for a particular user
> Participants: Update get participant team ids function.

- apps/challenges/serializers.py
- tests/unit/challenges/test_views.py
#494 solved. @deshraj Please review the PR.
> ChallengePhase serializer: is_active field added in the Serializer.

- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/js/controllers/challengeHostTeamsCtrl.js
- frontend/src/js/controllers/teamsCtrl.js
fixes #488. After these changes it worked for me.
> Fixed pagination for all views (#488)

- frontend/src/js/route-config/route-config.js
Solved issue #473 
@aka-jain @deshraj  : Please review
> frontend(logout): Unexpected logout issue has been resolved

- settings/prod.py
#522 solved. @deshraj Please review the PR.
> Name of memcached location environment Variable Modified.

- apps/hosts/views.py
- tests/unit/hosts/test_views.py
> Changed Serializer and Test

- apps/participants/views.py
- tests/unit/participants/test_views.py
> changed Serializer and test for same

- frontend/src/js/controllers/authCtrl.js
- frontend/src/views/web/login.html
- frontend/src/views/web/signup.html
#501 solved. @aka-jain @spyshiv Please review the PR.
> Auth Messages: When all fields are blank then message shown.

- frontend/src/views/web/login.html
- frontend/src/views/web/signup.html
@deshraj Please merge this.
PS: I working on minor issues of error messages in auth pages
> Frontend(fix): Fix blocking login/signup function due to PR #505

- frontend/src/js/controllers/challengeHostTeamsCtrl.js
- frontend/src/views/web/challenge-host-teams.html
URL & method paramters are empty when the API for inviting user to host team will be ready we can put it !
#477 resolved, please review!
> Fix:Added Functionality for inviting users to Host Team (#477)

- frontend/index.html
> Added global variable for GA

- frontend/src/views/web/partials/sidebar.html
> Removed arrow icon from profile

- frontend/src/views/web/partials/dyn-header.html
@deshraj @spyshiv  Please review
> Added auth based dashboard navigation

- frontend/src/css/modules/sidebar.scss
- frontend/src/css/modules/teams.scss
- frontend/src/js/controllers/teamsCtrl.js
- frontend/src/js/route-config/route-config.js
- frontend/src/views/web/teams.html
@spyshiv @deshraj Please review!
> Pagination for Participant team view.

- frontend/src/js/controllers/authCtrl.js
- frontend/src/js/directives/validation.directives.js
- frontend/src/views/web/login.html
- frontend/src/views/web/reset-password-confirm.html
- frontend/src/views/web/reset-password.html
- frontend/src/views/web/signup.html
Solution for issue #546 , #442 
@deshraj @aka-jain : Please review and test it in your devserver.
Modules to be tested are-
1. Login
2. Signup
3. Reset password
4. Reset Password Confirm
Please comment below in case of any issue.
> Frontend(Auth): Add error handling using ng-messages in auth pages

- scripts/migration/set_team_name_unique.py
Added Correct Path Added in Migration Scripts.
> Correct Path Added in Migration Scripts.

- frontend/src/js/controllers/mainCtrl.js
- frontend/src/views/web/landing.html
@deshraj  @aka-jain #560 resolved please review!
> Fix: Modal Created for Host Competition button on Homepage (#560)

- frontend/src/js/controllers/challengeHostTeamsCtrl.js
- frontend/src/views/web/challenge-host-teams.html
> Added pagination for host teams

- requirements/common.txt
> Added PyYaml-3.12 in requirements/common.txt

- frontend/src/css/modules/base.scss
- frontend/src/css/modules/challenge.scss
- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/js/route-config/route-config.js
- frontend/src/views/web/challenge-page.html
- frontend/src/views/web/challenge/my-submission.html
> Added my submission view

- frontend/src/js/route-config/route-config.js
- frontend/src/views/web/about-us.html
- frontend/src/views/web/dashboard-about-us.html
- frontend/src/views/web/partials/dashboard-footer.html
- frontend/src/views/web/partials/footer.html
fixes. #598  @aka-jain @spyshiv @deshraj  Please review the PR.
Moreover, @aka-jain Do I also need to create a separate `about-us` page for the footer `About-Us` link in the `landing page`?
> About Us: About us Page created.

- apps/jobs/sender.py
- apps/jobs/views.py
@deshraj @dexter1691 : please review
> Jobs: Add publisher to send submission message.

- frontend/src/js/route-config/route-config.js
- frontend/src/views/web/our-team.html
- frontend/src/views/web/partials/dashboard-footer.html
- frontend/src/views/web/partials/footer.html
#565 is solved @aka-jain please review
> Create a route and View for Our Team Page

- CONTRIBUTING.md
fixes #609. @aka-jain @spyshiv @deshraj  Please review the PR.
> Updated Contribution Guidelines: Added instructions to install HTML/CSS/JS Pretifier.

- frontend/src/js/directives/directives.js
- frontend/src/views/web/landing.html
- frontend/src/views/web/partials/dashboard-footer.html
- frontend/src/views/web/partials/footer.html
- frontend/src/views/web/web.html
This PR is regarding a feature to show the number of forks and stars on EvalAI on the footer which was mentioned in #568 .
> fixed #568

- README.md
fixes #624 . @deshraj @spyshiv Please review the PR.
> Project Setup: Updated Version of PostgresSQL to 9.4 in README

- frontend/src/css/modules/base.scss
- frontend/src/css/modules/sidebar.scss
- frontend/src/css/modules/variables.scss
> Sidebar Redesigned

- apps/web/templates/error404.html
- apps/web/templates/error500.html
- apps/web/views.py
- evalai/urls.py
- tests/unit/web/test_views.py
@deshraj Please Review this PR.
> Added Custom 404 and 500 Error Page

- frontend/src/js/controllers/authCtrl.js
> remove undefined reponse from controller

- frontend/src/css/modules/sidebar.scss
- frontend/src/css/modules/variables.scss
> Reverting back new design

- frontend/base.html
- gulpfile.js
- package.json
Solution for issue #536 
* Add dynamic js & css file path injection in main index.html
* Add base.html which will build index.html after `gulp inject`
* Run gulp tasks synchronously
* File compression feature added for production
* Remove unwanted code
@aka-jain / @deshraj Please review and merge
> Frontend(Gulp): Improved gulp tasks

- gulpfile.js
@deshraj @aka-jain Please merge this
> Fix(gulp inject): Add rootslash in static path injection

- frontend/src/js/controllers/authCtrl.js
- frontend/src/js/controllers/challengeCreate.js
- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/js/controllers/challengeHostTeamsCtrl.js
- frontend/src/js/controllers/challengeListCtrl.js
- frontend/src/js/controllers/changePwdCtrl.js
- frontend/src/js/controllers/dashCtrl.js
- frontend/src/js/controllers/mainCtrl.js
- frontend/src/js/controllers/profileCtrl.js
- frontend/src/js/controllers/teamsCtrl.js
- frontend/src/js/controllers/webCtrl.js
- frontend/src/js/directives/directives.js
- frontend/src/js/filters/filters.js
- frontend/src/js/route-config/route-config.js
- frontend/src/js/services/services.js
- frontend/src/js/services/validation-services.js
fixes #655 . @aka-jain @spyshiv Please review the PR.
> gulp lint warnings and errors removed.

- README.md
> Update README: RabbitMQ instructions added 

- README.md
- apps/hosts/views.py
> Fix: Show all Challenge Host Teams of a user

- bower.json
- frontend/app.scripts.json
- frontend/app.styles.json
- frontend/base.html
- frontend/src/css/modules/base.scss
- frontend/src/js/app.js
- frontend/src/js/controllers/authCtrl.js
- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/js/controllers/challengeHostTeamsCtrl.js
- frontend/src/js/controllers/teamsCtrl.js
- frontend/src/js/route-config/route-config.js
- gulpfile.js
Solution for #482 
@deshraj Please review
> Frontend: Add ui notification feature 

- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/js/route-config/route-config.js
@deshraj @spyshiv Please review this PR.
> Frontend: Removed Comparison Operator in case of "true" and "false".

- frontend/src/js/route-config/route-config.js
@deshraj / @spyshiv Please review!
> Removed eslint error from routers

- frontend/src/js/route-config/route-config.js
@aka-jain @deshraj Please review the PR.
> Removed Eslint Warning with route-config.js file.

- frontend/src/js/controllers/authCtrl.js
- frontend/src/js/controllers/challengeCtrl.js
> Frontend: Leaderboard and my-submission view polling fixed

- frontend/src/css/main.scss
- frontend/src/css/modules/notification.scss
- frontend/src/js/route-config/route-config.js
@aka-jain Please review this PR.
> Changed style/design of Notification system.

- frontend/src/views/web/about-us.html
> Fix: Footer Aligned for About Us Page (#714)

- apps/challenges/serializers.py
- tests/unit/challenges/test_models.py
- tests/unit/challenges/test_views.py
fixes #725 . @deshraj Please review the PR.
> Challenge App: Added fields in the ChallengePhaseSerializer.

- frontend/src/views/web/challenge/phases.html
@deshraj @aka-jain Please review the PR.
> Added details in challenge phase view.

- gulpfile.js
@deshraj Please review and merge
> Frontend: Add gulp script to minify prod config file

- frontend/src/js/controllers/updateProfileCtrl.js
- frontend/src/js/route-config/route-config.js
- frontend/src/views/web/partials/sidebar.html
- frontend/src/views/web/update-profile.html
fixes #649 . @deshraj @aka-jain @spyshiv Please review the PR.
> Update Profile: API endpoint Integrated with Client Side.

- frontend/src/js/controllers/authCtrl.js
- frontend/src/js/controllers/challengeCreate.js
- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/js/controllers/challengeHostTeamsCtrl.js
- frontend/src/js/controllers/challengeListCtrl.js
- frontend/src/js/controllers/changePwdCtrl.js
- frontend/src/js/controllers/dashCtrl.js
- frontend/src/js/controllers/mainCtrl.js
- frontend/src/js/controllers/teamsCtrl.js
- frontend/src/js/controllers/webCtrl.js
- frontend/src/js/route-config/route-config.js
@spyshiv @aka-jain Please review this PR.
> Removed jslint errors and cleaned code.

- frontend/src/js/route-config/route-config.js
> Frontend: Fix typo of logout notification

- docs/setup.md
To update user and password in sample settings `postgres` and `postgres`
> Docs: Add verbose setup docs.

- frontend/src/css/modules/main-header.scss
@deshraj @aka-jain @spyshiv Please Review the PR.
> Changed Position of Hamburger Icon from middle to left corner.

- frontend/src/css/modules/landing.scss
- frontend/src/views/web/partials/rocket-container.html
Done some small changes to rocket animation. Merging it directly.
> Added improved animation

- frontend/src/views/web/our-team.html
@spyshiv @aka-jain @deshraj Please Review the PR.
> Added footer in Our Team view.

- frontend/src/css/modules/landing.scss
@spyshiv @aka-jain Please review the PR.
> Changed position of rocket image in landing.scss file.

- docs/migrations.md
> Docs: Add guide about creating migrations.

- frontend/src/js/route-config/route-config.js
fixes #758 . @deshraj @spyshiv @aka-jain Please review the PR.
> Notification: Reduced time from 4 sec to 3 sec.

- frontend/src/views/web/partials/dashboard-footer.html
- frontend/src/views/web/partials/footer.html
@spyshiv @aka-jain Please review the PR.
> Linked Contact-Us view with Footer

- frontend/src/js/controllers/challengeHostTeamsCtrl.js
@spyshiv @aka-jain Please review the PR.
> Added space in Send Invite toaster message in Host Team.

- scripts/workers/submission_worker.py
- settings/common.py
Fixes #783 
The connection params are now moved to settings/common.py .
> Moves hardcoded connection params from worker to settings

- frontend/src/js/directives/directives.js
> Fix: Debugging Statements removed from directives (#765)

- gulpfile.js
Fixes #690 . @deshraj @spyshiv @aka-jain Please review the PR.
> Frontend: Merged 'gulp lint' task with 'gulp watch'.

- frontend/src/views/web/partials/dashboard-footer.html
> Remove facebook icon from dashboard footer

- .eslintrc
- frontend/src/js/controllers/authCtrl.js
- frontend/src/js/controllers/challengeCreate.js
- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/js/controllers/challengeHostTeamsCtrl.js
- frontend/src/js/controllers/challengeListCtrl.js
- frontend/src/js/controllers/changePwdCtrl.js
- frontend/src/js/controllers/dashCtrl.js
- frontend/src/js/controllers/mainCtrl.js
- frontend/src/js/controllers/permissionCtrl.js
- frontend/src/js/controllers/profileCtrl.js
- frontend/src/js/controllers/teamsCtrl.js
- frontend/src/js/controllers/updateProfileCtrl.js
- frontend/src/js/controllers/webCtrl.js
- frontend/src/js/directives/directives.js
- frontend/src/js/route-config/route-config.js
- frontend/src/js/services/services.js
> Revert "Removed Lint errors and Cleaned Code"

- frontend/src/js/controllers/ourteamCtrl.js
completes #817 . @deshraj Please merge this PR as it completes the lint errors in #817.
> Our team: Removed lint errors.

- scripts/workers/submission_worker.py
fixes #835 . @TroJan @deshraj  Please review the PR.
> Submission Worker: Changed Binding key for submission worker.

- frontend/src/css/modules/landing.scss
- frontend/src/views/web/join-our-team.html
@aka-jain @deshraj please review!
> Fix: Sticky footer added for join-us page(#824)

- frontend/src/css/core/grad-base.scss
- frontend/src/css/modules/landing.scss
- frontend/src/js/controllers/mainCtrl.js
- frontend/src/js/route-config/route-config.js
- frontend/src/js/services/services.js
- frontend/src/views/web/landing.html
@deshraj @spyshiv review please!
> Added Challenge Detail to home page

- frontend/src/css/modules/teams.scss
- frontend/src/js/controllers/challengeHostTeamsCtrl.js
- frontend/src/js/controllers/teamsCtrl.js
- frontend/src/views/web/challenge-host-teams.html
- frontend/src/views/web/teams.html
Fix for #371 
**Updated view:** 
`My Host Team`
`My Participant Team` 
**Screenshot:**
@deshraj @aka-jain : Please review.
> Frontend: Change team list to collapsible card layout to show extra details

- apps/web/serializers.py
- apps/web/views.py
- tests/unit/web/test_views.py
#890 Added the needed feature. Tested without "Headshot" and "Background images" due to lack of ability to mock the image data.
> Backend: Added API Endpoint to add contributors in Team list

- gulpfile.js
fixes #690 . @aka-jain @spyshiv Please review the PR.
> Server will not connect untill lint errors are solved.

- apps/base/utils.py
Currently, the stdout, stderr and result file of a submission are not
saved in the respective submission directory on server. This patch
fixes the problem.
> Base: Fix submission file path issue

- apps/jobs/views.py
- tests/unit/hosts/test_urls.py
> Remove unnecessary print statements from views and tests

- scripts/workers/submission_worker.py
> submission_worker.py: Add logging statements instead of print statements

- frontend/src/js/controllers/challengeCtrl.js
Fixes #984 
@deshraj have a look please!
> Frontend: Solved first time submission issue

- scripts/workers/submission_worker.py
@deshraj : this message prevents worker from blocking the queue(not acking the message) when a message of Submission which does not exist is published.
> Submission Worker: Proper error handling in case

- frontend/src/views/web/partials/main-header.html
Fix: #985 @aka-jain @deshraj Please review the PR.
> Frontend: Added profile page link to 'hi user' on landing page.

- frontend/src/js/controllers/authCtrl.js
- frontend/src/views/web/partials/main-header.html
- No element in DOM for `Logout` button till the user is authenticated.
- Replaced `ng-show/hide` by `ng-if`.
@deshraj @aka-jain Kindly review. :)
------ Signed off by @angularboy--------
> Fix #982: Removes the view bug on first load

- gulpfile.js
- package.json
Fix for #993 
@aka-jain / @deshraj  : Please review and run the whole project and let me know if any css failure occurs.
Also please let me know if you need more details regarding this PR.
Note: First of all please run `npm install` to install new dependency.
> Frontend: Integrate purifycss to remove unused css

- apps/challenges/models.py
- apps/hosts/models.py
- apps/web/models.py
> Fix: Replace %s with string format {} across all str functions of app models

- tests/unit/participants/test_models.py
tests for unicode have been added for the following classes:
1. Participant
2. ParticipantTeam
#1002
> Fix: Add tests for __unicode__ functions in participants model.

- tests/unit/web/test_models.py
tests for unicode have been added for the following classes:
1. Contact
2. Team
Should I leave out BaseTestCase or preserve for future additions?
#1002
> Fix: Add tests for __unicode__ functions in web model.

- tests/unit/accounts/test_models.py
Tests for unicode have been added for the following classes:
1. Profile
2. UserStatus
#1002
> Fix: Add tests for __unicode__ functions in accounts model.

- tests/unit/challenges/test_models.py
Last of the PR for issue #1002
> Fix: Add tests for __unicode__ functions in Challenge.LeaderboardData model.

- apps/base/utils.py
@deshraj @TroJan Please review the PR.
> Base app : Add a object checking and returning function.

- tests/unit/challenges/test_urls.py
> Fix: Inconsistency in unittests for URL Patterns.

- apps/challenges/admin.py
- apps/hosts/admin.py
- apps/jobs/admin.py
- apps/participants/admin.py
- requirements/common.txt
- settings/common.py
fixes #1053 . @deshraj @taranjeet Please review the PR.
> Add django-import-export.

- apps/base/models.py
- apps/challenges/models.py
fixes #839.
This PR also incorporates the reviews from PR #912 .
> [REVIEW PENDING] Challenges: Logs change in Challenge and Challenge Phase model when file fields are updated.

- apps/challenges/admin.py
- apps/hosts/admin.py
- apps/jobs/admin.py
- apps/participants/admin.py
- apps/web/admin.py
@RishabhJain2018 : please have a look at it
> Admin: Update ModelAdmin class for various models.

- apps/challenges/utils.py
> Add Challenge and ChallengePhase model getting functions.

- apps/challenges/serializers.py
fixes #1036 @deshraj @taranjeet Please review the PR.
> [REVIEW PENDING] Zip Challenge: Add new serializers for creating challenge.

- apps/hosts/utils.py
@deshraj @taranjeet Please review the PR.
> [REVIEW PENDING]Add a ChallengeHostTeam Model getting function in hosts utils.

- apps/challenges/serializers.py
This PR adds the minor fix in `ChallengeConfigSerializer` which was missed in PR #1035 and it will be used in creation of challenge using zip file.
> [REVIEW PENDING]Add Minor fix in ChallengeConfigSerializer.

- apps/hosts/utils.py
> Add function to check if user is Challenge host.

- apps/jobs/serializers.py
This PR fixes the minor bug in PR #1032 in the jobs serializer `ChallengeSubmissionManagementSerializer`.
> Minor fix in jobs ChallengeSubmissionManagementSerializer.

- apps/jobs/serializers.py
I apologise for the last PR. Actually, due to my text editors multiple edit, it changed the names wrongly.
These are the final and correct names.
Also, for further reference please see PR #1063 and #1032.
> Jobs: Fix variable name in ChallengeSubmissionManagementSerializer.

- frontend/src/views/web/partials/main-header.html
> Added profile link on Home page

- apps/challenges/serializers.py
- tests/unit/challenges/test_views.py
@deshraj @taranjeet Please review the PR.
> Modify challenge serializers to accept file input.

- apps/challenges/utils.py
- tests/unit/challenges/test_utils.py
@deshraj @taranjeet Please review the PR.
> Add a file reading function in challenge utils.

- apps/challenges/urls.py
- apps/challenges/views.py
- apps/hosts/utils.py
- apps/jobs/serializers.py
- tests/unit/challenges/test_views.py
fixes #850  @deshraj @taranjeet Please review the PR.
> [REVIEW PENDING] Add an API endpoint to show all the submissions to Challenge Host for a particular Challenge.

- docs/architecture.md
- docs/architecture_decisions.md
- docs/directory_structure.md
- docs/glossary.md
These are just draft of the docs, Will be updating in this PR only.
> Better docs.

- apps/analytics/urls.py
- apps/analytics/views.py
- apps/participants/serializers.py
- tests/unit/analytics/test_views.py
@deshraj @RishabhJain2018 : api to get participant count for a particular challenge.
> Analytics: Add api to get no of participants for a particular challenge.

- apps/analytics/urls.py
- apps/analytics/views.py
- apps/jobs/serializers.py
- tests/unit/analytics/test_views.py
> Analytics: Add API to get submission count for a particular challenge.

- frontend/src/js/controllers/challengeCreate.js
@deshraj @aka-jain Please review the PR.
> Fix lint errors for development.

- docs/source/setup.md
Please review. This actually the side navigation for Setup to display Fedora and Ubuntu setup instructions under it like
Setup
* ubuntu
* fedora
Plus some minor formatting.
> Docs: Update setup doc for better side navigation and heading structure.

- apps/challenges/admin.py
@deshraj @RishabhJain2018 
Also @RishabhJain2018 : if this PR is fine and merged, can you do the same for other apps as well ?
> Challenges: Use ImportExportTimeStampedAdmin for model admin class

- README.md
fixes #1095 . @deshraj @taranjeet Please review the PR.
> Add Read the Docs Badge.

- frontend/src/views/web/challenge-create.html
> Add link for challenge creation using zip documentation.

- apps/participants/urls.py
- apps/participants/views.py
- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/views/web/challenge/my-challenge-all-submission.html
- tests/unit/participants/test_urls.py
- tests/unit/participants/test_views.py
fixes #1107 @deshraj @taranjeet @aka-jain Please review the PR.
> Add check to show all submissions to challenge host only.

- apps/jobs/urls.py
- tests/unit/jobs/test_urls.py
> Typo fix in jobs urls.

- apps/hosts/admin.py
- apps/jobs/admin.py
- apps/participants/admin.py
- apps/web/admin.py
fixes #1103 @deshraj @taranjeet Please review the PR.
> Add Import Export Time Stamped Admin class to all apps.

- frontend/src/views/web/challenge/participate.html
Fix Typo error from  'Create Participaant Team' to 'Create Participant Team' in participant.html
> Fix #1108: Typo fix in participant.html

- apps/challenges/urls.py
- apps/challenges/views.py
- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/views/web/challenge/my-challenge-all-submission.html
- tests/unit/challenges/test_urls.py
- tests/unit/challenges/test_views.py
fixes #1109 . @deshraj @taranjeet @aka-jain @spyshiv  Please review the PR.
> Add support for exporting all submissions to csv file.

- .gitignore
- frontend/src/css/modules/submission.scss
- frontend/src/js/controllers/challengeCtrl.js
> fix #1117 : scss syntax error

- frontend/src/js/controllers/challengeCtrl.js
> Fix #1119 : submission url

- scripts/seed.py
Fixes #1143
To check, flush the existing db and run the seed script again.
@deshraj Please review.
> Fix #1143 : add approved by admin true in seed script

- scripts/workers/submission_worker.py
@RishabhJain2018 Please check.
Fix #1161
> Fix #1161 : enable admin check in worker script

- README.md
Add python 2.x requirement in README.md Fix #1147.
> Fix #1147 README update

- docs/source/evaluation_scripts.md
> Docs: Add evaluation script.

- docs/source/challenge_creation.md
Fix #1146. Link to the repository of creating challenge examples added in the docs.
> Link to example added in the creating challenge docs.

- frontend/src/js/controllers/challengeCtrl.js
fixes #1187 . @deshraj @aka-jain @spyshiv Please review the PR.
Please take a look!
> Fix console error after seeing the time remaining for the next submissions.

- apps/challenges/views.py
- apps/jobs/serializers.py
- tests/unit/challenges/test_views.py
fixes #1181 @deshraj Please review the PR.
> Add new fields in csv file data.

- apps/challenges/serializers.py
- apps/challenges/urls.py
- apps/challenges/views.py
- tests/unit/challenges/test_urls.py
- tests/unit/challenges/test_views.py
fixes #1183 @deshraj Please review the PR.
> Add API to star and unstar challenge.

- apps/challenges/views.py
- tests/unit/challenges/test_views.py
Fix #1155 . @deshraj Please review the PR.
> Remove pagination from challenge phase split list API.

- frontend/src/views/web/challenge/leaderboard.html
Fix #1205. @deshraj Please review the PR.
> Fix leaderboard phase error

- apps/challenges/views.py
- tests/unit/challenges/test_views.py
Fix #1210 . @deshraj Pleease review the PR.
> Add check for approve_by_admin and published in challenge analytics home.

- frontend/src/css/modules/auth.scss
- frontend/src/views/web/auth/auth.html
@deshraj @spyshiv please review.
> Enhancement: Added responsive auth pages

- frontend/src/views/web/featured-challenge/leaderboard.html
Fix #1218. @deshraj Please review the PR.
> Fix leaderboard in featured challenge.

- frontend/src/js/controllers/challengeCtrl.js
Fix #1255 @deshraj Please review the PR.
> Url fix in challenge controller for remaining submissions

- frontend/src/js/controllers/authCtrl.js
Cleaning the some ```console.log``` from code.
> Clear code: Removing statements used to debugging.  Fix #1259 .

- apps/jobs/models.py
- requirements/common.txt
> Jobs: Use cached_property from django.utils.functional

- tests/unit/jobs/test_views.py
> Fix runtime errors while running tests

- frontend/src/views/web/landing.html
`EvalAI is an open-source web platform for organizing and participating in competitions to push the state of the art on AI tasks.` -->  `EvalAI is an open-source web platform for organizing and participating in AI challenges. EvalAI = evaluating the state of the art in AI.`
> Minor language changes 2

- frontend/src/views/web/landing.html
`What is EvalAI all about?` --> `What is EvalAI?`
> Minor change to language

- apps/challenges/admin.py
> Fix #1304 add featured field to django-admin panel for list filtering

- README.md
> Fix #1308: update docker section of README.md

- bower.json
- frontend/app.scripts.json
- frontend/app.styles.json
- frontend/src/js/app.js
This commit reverts commit aa95cf2ee7aeb4558f4ee4f8d61a7c1ecc70d7b3(Fix #1257: Add new dependencies for date-time picker and trix editor. (#1258)).
@deshraj Please merge it asap, as the app is breaking due to #1258  commit.
> Revert "Fix #1257: Add new dependencies for date-time picker and trix editor. (#1258)

- README.md
> Add python version warning in README

- bower.json
- frontend/app.scripts.json
- frontend/app.styles.json
- frontend/src/js/app.js
Fix #1323 . @deshraj @aka-jain @spyshiv  Please review the PR.
> Add dependency for Angular trix text editor.

- docs/source/architecture_decisions.md
> Fix #1333:  Fix CRUD typo's in architecture_decisions doc

- apps/analytics/serializers.py
- apps/analytics/views.py
- apps/jobs/models.py
- frontend/src/js/controllers/analyticsCtrl.js
- tests/unit/analytics/test_views.py
Improves the response time from 10 seconds to 540 ms.
> Analytics: Optimize queries to get Submission count

- frontend/src/js/controllers/challengeListCtrl.js
> Fix #1374: Remove stale code related to background

- frontend/src/js/controllers/challengeListCtrl.js
> Fix #1374: Remove stale code related to the background

- docs/source/architecture.md
- docs/source/challenge_creation.md
- docs/source/glossary.md
I fixed some minor errors in the grammar and formatted some lists that were not using proper Markdown.
> Glossary, Architecture, and Challenge Documentation

- frontend/src/css/modules/base.scss
- frontend/src/views/web/challenge-host-teams.html
- frontend/src/views/web/teams.html
Changed rectangular buttons to circular
> Changed rectangular buttons to circular

- docs/source/architecture_decisions.md
Here are some grammatical changes in the file.
Thanks!
>  Reporting some grammatical mistakes

- docs/source/architecture.md
The PR fixes #1383  
Few grammatical errors corrected in architecture.md Please review :)
Thanks!
> Fix#1383: Grammatical errors resolved in docs

- docs/source/architecture.md
- docs/source/architecture_decisions.md
- docs/source/challenge_creation.md
- docs/source/contribution.rst
- docs/source/directory_structure.md
- docs/source/evaluation_scripts.md
- docs/source/glossary.md
- docs/source/migrations.md
- docs/source/pull_request.md
- docs/source/setup.md
- docs/source/submission.md
> Fix grammatical mistakes in EvalAI docs

- frontend/src/views/web/challenge-create.html
> Grammar Fix Challenge Create

- frontend/src/js/controllers/challengeCreate.js
> Fix #1289: Show a loader when a challenge zip configuration is submitted

- README.md
Fix #1448 @deshraj @aka-jain Please review and merge it!
> Add links to portfolio websites of maintainers.

- frontend/src/views/web/get-involved.html
- frontend/src/views/web/landing.html
Made the link blue coloured and added some more description for EvalAI!! #1456 Fixed!!
@RishabhJain2018 @aka-jain
> #1456 Fixed Updated Text

- frontend/src/css/modules/my-challenge-all-submission.scss
- frontend/src/views/web/challenge/my-submission.html
Fixes #1425.
Fixed screenshot:
> Fix #1425: Add card to my submissions

- .github/PULL_REQUEST_TEMPLATE.md
> Fix #1461 Updated the Link

- frontend/src/js/controllers/updateProfileCtrl.js
- frontend/src/views/web/profile.html
- frontend/src/views/web/update-profile.html
Fix #886  @deshraj @aka-jain @spyshiv Please review the PR.
> Add feature to update affiliation in profile.

- frontend/src/views/web/challenge-create.html
#1477 @spyshiv @RishabhJain2018 Please review the PR.
> Frontend: Updated hyperlink in info provided in create challenge with Zip file.

- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/views/web/challenge/edit-challenge/edit-challenge-phase.html
- frontend/src/views/web/challenge/phases.html
Fixes: #1342 
1.
2.
3.
4.
5.
6.
7.
8.
> Fix #1342: Add frontend for editing a challenge phase details.

- requirements/dev.txt
> Fix #1518: Add recommonmark to dev requirements

- frontend/src/css/modules/landing.scss
fix #1515 
@aka-jain @spyshiv please review
> Fix #1515: fixed unresponsive see-more button

- frontend/src/js/directives/directives.js
- frontend/src/views/web/partials/dashboard-footer.html
- frontend/src/views/web/partials/footer.html
> Fix #1373: 403 Forbidden response from Github API

- frontend/src/views/web/landing.html
- In home page, featured's view more link redirected to a broken link as ChallengeId was entered incorrectly in frontend.
Fixes #1524
> Small glitch in view more link

- apps/base/utils.py
- settings/common.py
Support for PR's #1489 and #1414 for storing admin E-mail and functions for encoding and decoding data, since this part is common to both.
> Support for PR's #1489 and #1414.

- apps/jobs/views.py
- frontend/src/views/web/challenge/leaderboard.html
- frontend/src/views/web/featured-challenge/leaderboard.html
Fix #1533 . @deshraj Please review it.
> [WIP] Add submitted_at field in the leaderboard.

- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/js/route-config/route-config.js
- frontend/src/views/web/challenge/leaderboard.html
Fix #1554 . @deshraj @spyshiv  Please review the PR.
> Add support to share challenge phase leaderboard

- apps/accounts/static/accounts/css/main.css
- apps/web/templates/notification_email.html
- apps/web/templates/notification_email_conformation.html
- apps/web/templates/notification_email_data.html
- apps/web/urls.py
- apps/web/views.py
- tests/unit/web/test_views.py
Fix #1549. @deshraj Please review the PR.
> Add feature to notify Users about new challenge via email.

- apps/participants/views.py
- tests/unit/participants/test_views.py
> FIX: Delete participant team when the last participant leaves the team.

- bower.json
- frontend/app.scripts.json
- frontend/src/css/modules/base.scss
- frontend/src/js/app.js
- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/js/controllers/featuredChallengeCtrl.js
- frontend/src/views/web/challenge/leaderboard.html
- frontend/src/views/web/featured-challenge/leaderboard.html
Fix #1552 . @deshraj Please review the PR.
Also, this commit doesn't include the fourth point in the issue. I am adding it in another commit in this PR only.
> Modify Leaderboard UI to show the details prettier

- scripts/workers/submission_worker.py
> Fix #1561: Improve dataset_split selection logic in submission worker

- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/js/controllers/featuredChallengeCtrl.js
- frontend/src/views/web/challenge/leaderboard.html
- frontend/src/views/web/featured-challenge/leaderboard.html
@deshraj Please review the PR. It fixes the bug in leaderboard.
> Fix bug in leaderboard UI in last_submission_at field

- frontend/src/views/web/challenge/evaluation.html
- frontend/src/views/web/challenge/phases.html
- frontend/src/views/web/challenge/submission.html
Fix #1584. @deshraj Please review the PR.
> Modify challenge evaluation and phase page

- frontend/src/js/controllers/challengeCtrl.js
Fix #1582. @deshraj Please review the PR.
> Fix bug in showing total submissions done to a challenge phase

- frontend/src/css/modules/base.scss
- frontend/src/views/web/challenge/submission.html
Fix #1586 . @deshraj Please review the PR.
> Fix display for showing remaining submissions.

- .gitignore
- settings/common.py
> Fix #1529: Modify logging path to prevent logging error

- apps/jobs/views.py
- tests/unit/jobs/test_views.py
> Fix #1599: Debug remaining submissions logic in backend

- frontend/src/js/controllers/permissionCtrl.js
- frontend/src/views/web/permission-denied.html
This reverts commit ce02c299dd557aed25c1cf3d3dc04ee7cca95478.
> Revert "Fix #630: Add frontend for resend email feature. (#1354)"

- settings/__init__.py
> Fix development runserver error

- apps/challenges/views.py
- tests/unit/challenges/test_views.py
> Fix #1627 #1638: Update the challenge creation API to handle missing fields

- docs/source/faq(developers).md
- docs/source/index.rst
Fixes #1130 .
Added a FAQ page for Developers including Common Errors during Installation.
@deshraj @RishabhJain2018 .
> Fixes #1130 FAQ page for Developers

- docs/source/challenge_creation.md
> Remove redundant leaderboard field from the challenge creation docs

- apps/accounts/static/accounts/css/main.css
- bower.json
- frontend/app.scripts.json
- frontend/src/css/modules/profile.scss
- frontend/src/js/app.js
- frontend/src/js/controllers/profileCtrl.js
- frontend/src/views/web/auth/get-token.html
- frontend/src/views/web/profile.html
> Frontend for show auth token.

- frontend/src/css/modules/base.scss
Fix #1724. @deshraj Please review the PR.
> Increase width of horizontal scrollbar

- frontend/src/views/web/challenge-host-teams.html
- frontend/src/views/web/teams.html
Fix #1721 . @deshraj Please review the PR.
> Allow support for . in team names

- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/views/web/challenge/submission.html
Fix #1727 @deshraj Please review the PR.
> Fix Error message on first phase click under submit tab

- apps/jobs/views.py
This PR improves the way we filter the submissions to be shown on the leaderboard. Also makes our system more robust. :)
> Jobs: Update the filtering logic for showing entries on leaderboard

- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/js/controllers/teamsCtrl.js
- frontend/src/views/web/challenge/leaderboard.html
This fixes the challenge-leaderboard sorting issue (while switching sort between different columns).
cc: @RishabhJain2018 @deshraj
> Leaderboard sort fix

- frontend/src/js/controllers/teamsCtrl.js
Fixes the minor typo issues introduced in #1730. 
cc: @RishabhJain2018 Please check the console warnings before creating pull requests. :)
> Frontend: Minor typo fixes

- docs/source/faq(developers).md
- docs/source/index.rst
- docs/source/pull_request.md
Fixed spacing and typos in the docs
> Fixed typos in the docs 

- apps/challenges/migrations/0019_added_leaderboard_data_table.py
- docker/dev/worker/Dockerfile
- scripts/workers/submission_worker.py
@deshraj @taranjeet Please review the PR.
> Fix Python3 migration error along with adding its support

- frontend/src/views/web/edit-teams.html
> Typo fix in edit team name

- scripts/deploy/deploy.sh
> Tag & push the docker images with latest & travis commit id tag

- docker/prod/django/container-start.sh
Added Short Circuit Behavior using Logical AND in  [docker/prod/django/container-start.sh](https://github.com/Cloud-CV/EvalAI/blob/master/docker/prod/django/container-start.sh)
Closes #1817
> Fix #1817 : Adding Short Circuit Behaviour

- frontend/src/views/web/contact-us.html
> Fixed the contact us page 

- scripts/workers/submission_worker.py
> Fix python3 import error

- apps/challenges/views.py
> Fix challenge creation using zip in python 3

- scripts/workers/submission_worker.py
> Revert "Fix python3 import error"

- requirements/common.txt
I upgraded django version 1.11.15. I tested on UI and checked logs of worker and django. Couldn't see any harm.
#1834
> Fix #1834: Upgraded django 1.11.15

- frontend/src/views/web/challenge/challenge-page.html
#1833  Remove discussions tab from challenge page
> hide discussions tab if link is null from backend

- scripts/workers/submission_worker.py
> Fix for saving correct submission result file

- apps/jobs/views.py
> Update Docs for the added API

- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/js/controllers/contactUsCtrl.js
- frontend/src/js/controllers/profileCtrl.js
- frontend/src/js/controllers/updateProfileCtrl.js
- frontend/src/js/controllers/webCtrl.js
Fix #1622 : Add response argument in onError functions in controllers for frontend wherever possible @isht3
> Fix #1622 Add response argument in onError functions in controllers for frontend

- frontend/src/views/web/analytics/host-analytics.html
DIsabled "Show Analysis" button when there are no hosted challenges
@RishabhJain2018 @erikaaatan @vkartik97
> Disbaled Button if there are no hosted challenges

- frontend/src/js/directives/directives.js
- frontend/src/views/web/partials/footer.html
Fixes #1878 
Removed hard coded year in footer and made it dynamic. - GCI
@RishabhJain2018 @vkartik97
> Dynamic Copyright Year

- frontend/src/views/web/landing.html
Mobile version of the EvalAI site will now have the “Host Challenge” and “Participate” buttons on the home screen. @RishabhJain2018 @vkartik97 @erikaaatan
> “Host Challenge” and “Participate” buttons visible in Mobile view

- frontend/src/js/directives/directives.js
- frontend/src/views/web/partials/dashboard-footer.html
Added Copyright Year in the Dashboard Footer. Fixes #1878 .
@RishabhJain2018 @deshraj
> Add Copyright Year in the Dashboard Footer

- frontend/src/views/web/edit-teams.html
Fixes #1714 .
@deshraj @RishabhJain2018
> Disable button when no change in team name

- frontend/src/js/controllers/challengeCtrl.js
Issue #1876 states about a bug in the backend that isn't relayed to the front end. PR fixes the issue by checking the length of string before submission.
> Fix #1876 : Filename too long issue displayed on Frontend

- apps/jobs/views.py
Fixes https://sentry.io/cloudcv/evalai/issues/784258070/?query=is:unresolved
> Add fix for missing submission status field

- docker-compose-production.yml
- scripts/deployment/deploy.sh
> Add production deployment ssl fixes

- apps/challenges/urls.py
- apps/challenges/views.py
Output Format:
```
[
"queue-name-1",
"queue-name-2",
]
```
> Add API for fetching broker URLS

- apps/challenges/urls.py
- apps/challenges/views.py
- scripts/deployment/deploy.sh
Output format:
```
[
"queue_name"
]
```
> Add API to get queue name by challenge pk and tooling around it.

- apps/accounts/admin.py
- apps/challenges/admin.py
- apps/jobs/admin.py
This PR introduces following changes:
> Import/Export: Minor improvements in import-export for different apps

- apps/jobs/admin.py
> Fix #1975: Adding Challenge name to Search Field and List Filter

- frontend/src/js/route-config/route-config.js
Fix #1977 
@deshraj Please review the PR. Also, can you please test it on your local before merging it.
> Fix back behaviour from landing page

- apps/challenges/views.py
- frontend/src/views/web/challenge/challenge-page.html
@RishabhJain2018 IMO there's no requirement of adding tests for these. If not so do let me know, I'll add them along 😅 
Closes #1964
> Fix #1964 View stars without login 

- docker-compose.yml
Currently, if you are running the nodejs container, then it doesn't pick the changes since we have not mapped port `35729` from the host machine to docker container. This Pull Request resolves that issue.
> Frontend: Allow live changes sync in docker container

- apps/analytics/views.py
- apps/challenges/views.py
- apps/hosts/views.py
- apps/jobs/models.py
- apps/jobs/views.py
- apps/participants/views.py
- settings/common.py
- settings/dev.py
> [WIP] Fix #1986  Test warning fix

- frontend/src/views/web/partials/dyn-header.html
- frontend/src/views/web/partials/main-header.html
- frontend/src/views/web/partials/sim-header.html
> Add challenge Tab in the header

- apps/jobs/serializers.py
fixes incorrect fields(#2011 )
> Fix #2011: Job Serializer Fixed

- frontend/src/views/web/challenge/participate.html
- frontend/src/views/web/challenge/submission.html
- frontend/src/views/web/featured-challenge/participate.html
- frontend/src/views/web/landing.html
> Fix #2036: Correcting Typos

- docs/source/approve_challenge.md
- docs/source/submission.md
>  Fix Docs bugs

- README.md
- apps/jobs/views.py
- tests/unit/jobs/test_views.py
1. Fix #2064
2. Display consistent public leaderboard for host and participant
> Display consistent public leaderboard for host and participant

- scripts/seed.py
> [WIP]Add challenge slug field in Seed script

- frontend/src/views/web/challenge/my-submission.html
Fixes https://github.com/Cloud-CV/EvalAI/issues/2126
@gautamjajoo @RishabhJain2018 Please review it.
> Fixes pagination button issue in challenges page

- tests/unit/jobs/test_views.py
Fix #2134 
Removed duplicates of self.challenge_phase.save()
> Fix #2134  Removed duplicates of self.challenge_phase.save()

- frontend/src/css/modules/auth.scss
Fix #2149 : Make the height of form input fields constant
> Fix input field height

- frontend/src/css/modules/main-header.scss
- frontend/src/views/web/partials/main-header.html
- frontend/src/views/web/partials/sim-header.html
@RishabhJain2018 Fix #2177 EvalAI is vertically centred in mobile view.
> Fix EvalAI vertical alignment

- settings/common.py
> Increase default pagination size to 100

- frontend/src/views/web/challenge/submission.html
Command to set_token fixed (closes #2214 )
> Fix #2214: Copy token command fixed

- scripts/workers/remote_submission_worker.py
> Fixes #2269: Remove django.setup() from remote_submission_worker.

- apps/jobs/views.py
- frontend/src/views/web/challenge/leaderboard.html
- tests/unit/jobs/test_views.py
This PR adds links the leaderboard entries with the team URLs if it is present.
> Link team-url with team-name on leaderboard

- frontend/app.scripts.json
Fixing Language in date-time calendar in challenge phase edit.
> Frontend: Fix date-time picker language

- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/js/controllers/challengeListCtrl.js
Fix #2311 @RishabhJain2018 Please review.
> Fix #2311: Fix travis build after #2296 is merged

- frontend/src/views/web/challenge/edit-challenge/edit-challenge-phase.html
Fix #2329 
here's a screencast of the working
> Fix #2329: Fix bug in editing phase details

- frontend/tests/controllers-test/SubmissionFilesCtrl.test.js
- frontend/tests/controllers-test/contactUsCtrl.test.js
**PR contains the front-end unit tests of:**
- Contact Us Controller (`contactUsCtrl.js`)
- Submission Files Controller (`SubmissionFilesCtrl.js`)
> Frontend: Add unit tests for contact us & submission files controller

- frontend/tests/controllers-test/featuredChallengeCtrl.test.js
- frontend/tests/controllers-test/hostedChallengeCtrl.test.js
**PR contains the front-end unit tests of:**
- Featured Challenge Controller (`featuredChallengeCtrl.js`)
- Hosted Challenge Controller (`hostedChallengeCtrl.js`)
> Frontend: Add unit tests for featured challenge & my hosted challenges controller

- frontend/tests/controllers-test/profileCtrl.test.js
- frontend/tests/controllers-test/webCtrl.test.js
PR contains the front-end unit tests of:
- Profile Controller
- Web Controller
> Frontend: Add unit tests for profile & web controller

- .github/CONTRIBUTING.md
> Add commit message guidelines in CONTRIBUTING.md file

- apps/jobs/views.py
> Revert "Add leaderboard sorting at last in API to avoid sorting errors"

- apps/jobs/views.py
- tests/unit/jobs/test_views.py
> Revert "Fix leaderboard sorting bug when the submissions are re-run"

- .github/stale.yml
- Changed the configuration of `stale.yml` because issues are created to get resolved and as they are not resolved so they should not be closed by the stale bot
> Changed the configuration of stale.yml

- frontend/src/js/controllers/challengeCtrl.js
Fixes: #2366 
This fix is similar to [Pull#1847](https://github.com/Cloud-CV/EvalAI/pull/1847).
> Fix #2366: Fix API endpoint URL for submission page

- apps/jobs/views.py
- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/views/web/challenge/my-challenge-all-submission.html
- frontend/src/views/web/challenge/my-submission.html
- Added the html code to filter by team name in `my-submission.html`
- Used the previously added django-filter in `challenge_submission` API to get the filtered querset
- Updated the js code to use the API url when some query parameter have been passed
**<p align="center">Screenshot</p>**
> Add a feature to filter the my submissions

- frontend/src/views/web/challenge/challenge-page.html
**Bug:** Participate and Submit tab on the challenge page are showing at the same time which should not be the expected behaviour.
- This PR fixes the logic related to showing submit and participate tab.
- Removed the unnecessary or condition for participate tab
> Fix logic related to showing submit and participate tab

- docs/source/architecture.md
- docs/source/host_challenge.md
- docs/source/intro.md
**Issue:**
Images are not showing up in the readme.
**Fix:**
To fix this removed the forward slash from the beginning of the URL of images
> Fix the url of images in the docs

- .github/stale.yml
**Issue:**
Stale bot is closing the issues which is not the expected behaviour
**Fix:**
Limited to only pull request by setting the `only: pulls` in `stale.yml` file
> Stale bot config: Fix stale bot configuration to not close the issues

- frontend/src/css/modules/challenge.scss
- frontend/src/views/web/challenge/evaluation.html
- frontend/src/views/web/challenge/overview.html
- frontend/src/views/web/challenge/phases.html
- frontend/src/views/web/challenge/submission.html
> Add blue color for the anchor tag present in the text of challenge page

- apps/jobs/views.py
Fixed `update_submission_status` endpoint
> Fix Update Submission Status Endpoint

- frontend/tests/controllers-test/webCtrl.test.js
- Removed the create controller at the start and stored `userKey` at the start
Reference: https://travis-ci.org/Cloud-CV/EvalAI/builds/561463897#L1823
> Fix the frontend failing tests of web controller

- apps/challenges/aws_utils.py
**Indent Code:** in this [commit](https://github.com/Cloud-CV/EvalAI/commit/bc92f0372f35b8e4b787de0e6ec1528f79d6c8ac)
1. Ran black on `apps/challenges/aws_utils.py` for code indentation.
2. Fix flake8 errors.
**Minor fixes for ECS deployment** in this [commit](https://github.com/Cloud-CV/EvalAI/commit/96c6441ed9bcadd5807c753b26bb494f1e0121fb)
1. Add `AWS_STORAGE_BUCKET_NAME` as an env variable.
2. Fix errors in `RDS_PASSWORD` and `RDS_USERNAME`
3. Add corner case for creating the challenge task def.
> Backend: Indent code & add minor fixes for ECS deployment.

- scripts/workers/submission_worker.py
> Fix submission worker file for downloading large submission files

- docker-compose-production.yml
- docker-compose-staging.yml
> Fix the environment variable file name in docker prod & staging config

- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/views/web/challenge/submission.html
> Fix regex for URL in Challenge Ctrl & fix text on submissions page

- docker-compose-production.yml
- docker-compose-staging.yml
- docker/prod/celery/Dockerfile
- scripts/deployment/deploy.sh
> Deployment: Fix scripts for pushing celery docker image

- settings/common.py
> Increase django upload limit to 4 GB & fix formatting in settings

- frontend/src/css/modules/leaderboard.scss
- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/views/web/challenge/leaderboard.html
Reverts Cloud-CV/EvalAI#2334
The staging build fails here: https://travis-ci.org/Cloud-CV/EvalAI/builds/591303993#L6045 due to this commit.
@Sanji515 Can you please fix this?
cc: @galipremsagar
> Revert " Fix #2143: Create a unique link for each of the entry on the leaderboard"

- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/js/controllers/featuredChallengeCtrl.js
- frontend/src/js/route-config/route-config.js
- frontend/src/views/web/challenge-list.html
- frontend/src/views/web/featured-challenge/participate.html
- frontend/src/views/web/hosted-challenges.html
- frontend/src/views/web/landing.html
> Revert "Add slug field for each challenge to have different URL for each challenge."

- README.md
> Readme: Remove code climate badge from Readme

- .travis.yml
Fixes the Travis build here: https://travis-ci.org/Cloud-CV/EvalAI/builds/598382803#L237
> Upadate java version from 9 to 11

- apps/challenges/permissions.py
- tests/unit/challenges/test_views.py
**Fix:**
The challenge host team members are able to edit the challenge and challenge phase details.
> Backend: Fix permissions for editing challenge details by host team members

- frontend/src/views/web/challenge/leaderboard.html
> Add check for challenge host to sort entries by latest or best

- frontend/src/js/controllers/challengeCtrl.js
> Add missing semi-colon to fix travis build

- apps/jobs/serializers.py
> Backend: Add error field in LeaderboardData serializer

- apps/challenges/views.py
- tests/unit/worker/test_submission_worker.py
* Added test for submission worker [`load_challenge_and_return_max_submissions`](https://github.com/Cloud-CV/EvalAI/blob/master/scripts/workers/submission_worker.py#L648)
* According to GCI task: 'Add test for load_challenge_and_return_max_submissions function for submission worker'
> [GCI] Added test for load_challenge_and_return_max_submissions

- docs/source/faq(developers).md
- frontend/src/views/web/get-involved.html
- frontend/src/views/web/profile.html
- frontend/src/views/web/update-profile.html
Simply replaced `Github` with `GitHub`.
> Fix GitHub Case

- apps/challenges/views.py
- tests/unit/worker/test_submission_worker.py
* As part of a GCI task.
* Added `test_extract_submission_data` to test function [`extract_submission_data` ](https://github.com/Cloud-CV/EvalAI/blob/master/scripts/workers/submission_worker.py#L275) from submission worker.
> [GCI] Add test for extract_submission_data

- requirements/common.txt
Add Kubernetes in python-client as requirements.
> Add kubernetes in requirements

- scripts/workers/rl_submission_worker.py
- scripts/workers/worker_util.py
Changes proposed in this PR:
- Fix import for `worker_util` file
- Remove port from Django server 
- Rename `DJANGO_SERVER` variable since we already have an env variable with this name.
- Indentation fixes
> Fixes in RL submission worker

- docs/source/architecture.md
<b>Changes proposed in this pull request: </b>
* Update Django version in architecture.md: Django 1.11.18 -> 1.11.23
Reference: https://github.com/Cloud-CV/EvalAI/blob/master/requirements/common.txt#L6
> Docs: Update architecture.md with correct Django version

- frontend/src/views/web/landing.html
Changes -
- Add statistics for the number of users using the platform, number of challenges hosted, number of organizations and number of submissions.
> Frontend: Add statistics on the landing page

- docker/prod/worker/Dockerfile
- requirements/worker.txt
> Update dependencies in worker container

- docker/prod/worker/Dockerfile
- requirements/worker.txt
Fix to #2680 
Travis Error: https://travis-ci.org/Cloud-CV/EvalAI/builds/651643351#L5630
> Fix numpy for pycocotools in worker

- requirements/prod.txt
Fixes to #2681, #2680 
Reference: https://github.com/getsentry/raven-python/issues/1277
> Update raven to work with python3.7 in worker

- requirements/common.txt
updates django-import-export tool (closes #2694 )
> Fix #2694: django-import-export updated

- scripts/workers/rl_submission_worker.py
> Add capability to fetch environment image from database in code upload challenge worker

- frontend/src/css/modules/base.scss
- frontend/src/views/web/challenge/challenge-page.html
- frontend/src/views/web/challenge/evaluation.html
- frontend/src/views/web/challenge/leaderboard.html
- frontend/src/views/web/challenge/my-challenge-all-submission.html
- frontend/src/views/web/challenge/my-submission.html
- frontend/src/views/web/challenge/overview.html
- frontend/src/views/web/challenge/participate.html
- frontend/src/views/web/challenge/phases.html
- frontend/src/views/web/challenge/submission.html
- frontend/src/views/web/challenge/terms-and-conditions.html
- frontend/src/views/web/featured-challenge/challenge-page.html
Updated UI Screencast: https://www.loom.com/share/402f5596e9f647019baf43eb5776a169
Some of the screenshots of the updated UI:
> [Frontend] Update challenge page UI

- frontend/src/views/web/challenge/evaluation.html
> [Frontend] Fix evaluation tab on challenge page

- docker/prod/celery/Dockerfile
- docker/prod/worker/Dockerfile
- scripts/deployment/push.sh
@RishabhJain2018 my last PR introduced this small issue which broke the image building on travis CI. Adding necessary changes here to fix it. 
Fix bugs in #2725
> [Docker] Fix docker push for production environment

- apps/challenges/serializers.py
- apps/challenges/urls.py
- apps/challenges/views.py
> Add API to get challenge evaluation cluster details

- scripts/workers/rl_submission_worker.py
- scripts/workers/worker_utils.py
> Integrate API for bearer token and cluster name with RL worker

- frontend/src/views/web/challenge/evaluation.html
- frontend/src/views/web/challenge/overview.html
- frontend/src/views/web/challenge/phases.html
- frontend/src/views/web/challenge/submission.html
- frontend/src/views/web/challenge/terms-and-conditions.html
This PR fixes minor issues from #2721 
cc: @deshraj
> add class to make anchor links appear in blue

- apps/base/utils.py
- apps/jobs/utils.py
> Change the submitted_at time to previous submission's submitted_at when a submission is rerun

- apps/jobs/utils.py
> Fetch URL from the file field

- apps/jobs/admin.py
> Add feature to cancel existing submissions from admin

- frontend/src/views/web/challenge/phases.html
> Fix UI for challenge phases

- .pre-commit-config.yaml
- frontend/src/views/web/challenge/evaluation.html
> Display hyperlink in blue for evaluation and terms and conditions page

- apps/jobs/views.py
- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/views/web/challenge/leaderboard.html
Enhancements:
GIF of enhancements:
> Enhancement in complete leaderboard [public/private]

- frontend/src/css/modules/notification.scss
- frontend/src/css/modules/variables.scss
- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/js/controllers/challengeHostTeamsCtrl.js
- frontend/src/js/route-config/route-config.js
- frontend/tests/controllers-test/challengeHostTeamsCtrl.test.js
Also added a bunch of typo fixes in the text shown in the notification.
> [Frontend] Improve notifications layout and colors

- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/views/web/challenge/my-challenge-all-submission.html
- frontend/src/views/web/challenge/my-submission.html
- frontend/src/views/web/partials/main-header.html
- frontend/src/views/web/partials/sim-header.html
Includes following changes:
- Fix Travis CI failing build due to js error 
- Improvements in naming conventions
- Remove unnecessary field `Team Name` on My Submissions Page
> [Frontend] Fix travis build and add minor improvements

- frontend/src/js/controllers/challengeCtrl.js
Fix: #2810 [ Bug in compressing files for production  ]
**Cause of bug**
`arrow_function` used for getting whether leadreboard is private or not [here](https://github.com/Cloud-CV/EvalAI/commit/5a78b2048461e95e7cc325fad264ce0c2055a879#diff-14a845646ed48757b5c7798b7ccdddb6R679)
**Fix of bug**
Replaced arrow function with an if-else function
Screenshot of result after running `gulp staging` in nodeJS container.
> Fix Bug in compressing files for production 

- scripts/deployment/deploy.sh
Missed to add a chmod for the pem file in the last PR. Changing the permission of the pem file before sshing to the instance.
Fixes to #2809
> [Travis CI] Fix autodeployment pipeline

- apps/jobs/sender.py
> Add submission ID in slack notification

- frontend/src/css/modules/base.scss
- frontend/src/js/controllers/challengeListCtrl.js
**Bug Description**
`Scroll Up` icon was not appearing even after being added in the `challenge-list` page.
**After Fix :**
`Scroll Up` button now appears behaves as expected.
GIF of fix:
> Fix scroll up in challenge list

- apps/accounts/templates/account/email_confirm.html
email confirmation page links back to main hosted instance bug fixed ( closes #1619 )
> #Fix 1619: email confirmation page link fixed

- apps/challenges/aws_utils.py
Adds background process for  cluster and nodegroup creation  closes(#2869)
> #2869: Background process added for cluster/ nodegroup creation

- docker-compose.yml
- frontend/src/css/modules/challenge.scss
- frontend/src/views/web/challenge/my-challenge-all-submission.html
- frontend/src/views/web/challenge/my-submission.html
Change color of submission status `partially_evaluated` to `royalblue` on frontend and show it as `Partially Evaluated` on Frontend instead of `Partially_evaluated`.
> [Frontend] Color change for partially_evaluated submission status

- apps/challenges/aws_utils.py
> Fix repititons while sending worker restart notification email.

- frontend/src/css/modules/base.scss
- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/views/web/challenge/challenge-page.html
- frontend/src/views/web/challenge/manage.html
- frontend/src/views/web/landing.html
> [Frontend] Update stats on home page and improve UI for manage tab

- frontend_v2/src/app/components/challenge/challengesubmissions/challengesubmissions.component.html
- frontend_v2/src/app/components/challenge/challengeviewallsubmissions/challengeviewallsubmissions.component.html
- frontend_v2/src/app/services/endpoints.service.ts
**Changes Introduced**
**Before**
_My submission page_
_All submission page_
**After**
_My submission page_
_All submission page_
cc: @deshraj @RishabhJain2018 @Sanji515 @lunayach @Shekharrajak
> [Frontend_v2] Improved submission UI

- docker-compose-staging.yml
- docker/prod/nodejs_v2/Dockerfile
- docker/prod/nodejs_v2/nginx.conf
- scripts/deployment/deploy.sh
- settings/staging.py
New frontend deployed to EvalAI staging server: http://evalai-staging-v2.cloudcv.org:9999
cc: @Ram81
> [Frontend V2] Setup new frontend on staging server along with older version

- apps/hosts/filters.py
- apps/hosts/views.py
- apps/participants/filters.py
- apps/participants/views.py
- frontend_v2/src/app/components/publiclists/teamlist/teamlist.component.html
- frontend_v2/src/app/components/publiclists/teamlist/teamlist.component.scss
- frontend_v2/src/app/components/publiclists/teamlist/teamlist.component.ts
- frontend_v2/src/app/services/endpoints.service.ts
**Changes introduced through this PR**
GIF:
\cc: @lunayach @RishabhJain2018 @Sanji515 @Shekharrajak
> [Frontend_v2]Filter teams on UI

- frontend_v2/src/app/components/challenge/challenge.component.html
- frontend_v2/src/app/components/challenge/challenge.component.scss
- frontend_v2/src/app/components/home/home.component.scss
**Changes Introduced**
- Removed `close_participation` from challenge detail as it is being moved to challenge settings tab.
- Minor UI enhancement
- Home page challenge card UI
Old UI:
Improved UI:
Challenge Card UI for Home Page:
Before:
After:
\cc: @RishabhJain2018 @Sanji515 @lunayach @Shekharrajak
> [Frontend_v2] Minor UI Fixes

- frontend_v2/src/app/components/challenge/challengesubmissions/challengesubmissions.component.scss
- frontend_v2/src/app/components/challenge/challengeviewallsubmissions/challengeviewallsubmissions.component.scss
**Changes Introduced through the PR**
- Submission page UI improved.
GIF of Improvement:
\cc: @RishabhJain2018 @Sanji515 @lunayach @Shekharrajak
> [Frontend_v2] Submission page UI Improved

- apps/base/management/commands/seed.py
- scripts/seed.py
Fixes #2944 
This PR adds the following improvements to seed script:
1. Add 5 ongoing featured challenges 
2. Fixes the challenge image not loading in seeded challenges bug
> [Seeding] Add featured challenges in seed script

- frontend_v2/src/app/components/home/home.component.html
- frontend_v2/src/app/components/home/home.component.scss
- frontend_v2/src/app/components/nav/header-static/header-static.component.html
- frontend_v2/src/app/components/nav/header-static/header-static.component.scss
- frontend_v2/src/styles/base.scss
- Improve code structure of home page component and related ts files
- Improve design layout for the home page
- Fix code smells and nav bar inconsistency issues
> [Frontend] Improve home page layout and add fix code smells

- apps/jobs/utils.py
- apps/jobs/views.py
- docker-compose.yml
Add custom sorting for submissions with status `RUNNING` `SUBMITTED` or `SUBMITTING` for `My submissions` page. Sorting logic (for submitting/submitted/running status challenge submissions -> sort by created_at asc -> return rank of current submission)
@RishabhJain2018 @deshraj
> [Backend] Rerank submissions In Progress on My Submissions page

- frontend_v2/src/app/components/challenge/challenge.component.html
- frontend_v2/src/app/components/challenge/challengeleaderboard/challengeleaderboard.component.html
- frontend_v2/src/app/components/home/home.component.html
- frontend_v2/src/app/components/nav/header-static/header-static.component.html
- frontend_v2/src/app/components/publiclists/challengelist/challengecard/challengecard.component.html
- frontend_v2/src/app/components/publiclists/challengelist/challengelist.component.html
- frontend_v2/src/app/components/utility/side-bar/side-bar.component.html
- frontend_v2/src/styles/base.scss
- Fix CSS for aligning the cards
- Improve challenge card styling and make them simpler
- Center align the content properly on large screens for the all challenges page
- Move all challenges link to the header (TODO: Move most of the navigation to the navbar)
- Change icons on the sidebar
https://www.loom.com/share/e20cc35e3bf7437bae2529c00252d32a
> [Frontend] UI improvements related to challenge cards

- apps/challenges/aws_utils.py
Passed deserialized `challenge_obj`
> Bug: challenge object deserialized in send email notification

- docker-compose-staging.yml
- frontend_v2/package.json
**Changes Introduced**
Before Fix:
After Fix:
\cc: @RishabhJain2018 @Ram81
> [Bug] Frontend_v2 error in staging environment

- .travis.yml
- docker/dev/nodejs/Dockerfile
- docker/dev/nodejs_v2/Dockerfile
**cause**
Missing `libxss1` dependency .
**solution**
Added `libxss1` dependency in dockerfile.
\cc: @Sanji515  @RishabhJain2018  @Ram81
> [Bug] Travis build Fail

- apps/challenges/aws_utils.py
updated keyname in the taskdefinition
> Bug: Fix key error in task definition

- scripts/workers/submission_worker.py
This PR changes submission worker log level to INFO to report all log messages on cloudwatch.
> Change submission worker log level to INFO

- scripts/workers/code_upload_submission_worker.py
- scripts/workers/code_upload_worker_utils/deploy_calico.sh
> Feature: ssl-verification added for kubernetes cluster

- apps/challenges/aws_utils.py
Fixes #2889 
Deletes log group after deleting the worker for a challenge.
@RishabhJain2018 @Ram81
> Add delete log group

- scripts/workers/code_upload_submission_worker.py
Updated the job_name field in the submission model to store Kubernetes generated name of a job
> Code upload worker: generate name added in submission models

- apps/challenges/aws_utils.py
Fixes #2977 
Adds check for docker based challenge in start_workers, restart_workers, stop_workers and delete_workers functions.
@RishabhJain2018 @Ram81
> Add check before worker methods

- apps/challenges/views.py
Fix for the template zip file url on staging and prod
- Do not append host url on staging and prod
> Fix for the template zip file url on staging and prod

- frontend/src/js/controllers/challengeCtrl.js
- frontend/tests/controllers-test/challengeCtrl.test.js
Currently, there is no check for missing file field in evaluation script update feature. This PR adds a check for missing file while updating evaluation script.
Fixes #2993
> Add check for missing evaluation script

- docker-compose.yml
> Remove commented code from dev setup

- docker/prod/nodejs_v2/Dockerfile
This PR fixes incorrect path for node modules in dockerfile for frontend v2
> [BugFix]: Fix node module path in frontend v2 production docker

- docker/prod/nodejs_v2/Dockerfile
- frontend_v2/src/environments/environment.prod.ts
- settings/prod.py
> Add production backend URLs in frontend

- frontend/src/views/web/landing.html
> Update stats on github homepage

- frontend/src/views/web/update-profile.html
This PR modifies the regex in update profile page to allow spaces in First name and Last name.
> [Frontend] Allow spaces in First and Last name

- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/views/web/challenge/submission.html
Reverts Cloud-CV/EvalAI#3012
The PR after deployment gives the error --
> Revert "[Frontend] Clear error message when selecting phase"

- frontend/src/js/route-config/route-config.js
> Fix the name conflict for route and controlleras

- frontend/src/js/route-config/route-config.js
Commented code related to "ChallengeInvitation" -- https://code.angularjs.org/1.7.0/docs/error/$injector/unpr?p0=challengeInvitation
> Add temporary fix for the staging server

- frontend/src/js/route-config/route-config.js
Reverts Cloud-CV/EvalAI#3017
This fix doesn't help.
> Revert "Add temporary fix for the staging server"

- frontend/src/js/controllers/ChallengeInviteCtrl.js
- frontend/src/js/controllers/SubmissionFilesCtrl.js
- frontend/src/js/controllers/authCtrl.js
- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/js/controllers/changePwdCtrl.js
- frontend/src/js/controllers/contactUsCtrl.js
- frontend/src/js/controllers/featuredChallengeCtrl.js
- frontend/src/js/controllers/updateProfileCtrl.js
- frontend/src/js/controllers/webCtrl.js
> Remove unnecessary injected dependencies from angular controllers

- frontend/base.html
- frontend/src/js/controllers/ChallengeInviteCtrl.js
- frontend/src/js/controllers/SubmissionFilesCtrl.js
- frontend/src/js/directives/directives.js
- frontend/src/js/route-config/route-config.js
- frontend/src/js/services/services.js
> Fix dependency injection error

- README.md
> Add twitter follow badge

- docs/source/installation.md
> Small change on installation instructions

- frontend/src/css/modules/submission.scss
- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/views/web/challenge/submission.html
- frontend_v2/src/app/components/challenge/challengesubmit/challengesubmit.component.ts
Required check for radio buttons and checkbox was not working for submission meta Attributes as the md-radio-group issue hasn't been fixed by angular [yet](https://github.com/angular/material/issues/1305). This PR adds a validation check
> Add required fields for meta attributes

- frontend/src/css/modules/submission.scss
- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/views/web/challenge/submission.html
- frontend_v2/src/app/components/challenge/challengesubmit/challengesubmit.component.ts
Reverts Cloud-CV/EvalAI#3027
@Ram81  seems like gulp staging is broken after your last PR. Here is the error:
```
Step 16/21 : RUN gulp ${NODE_ENV}
---> Running in c42bd591912f
[03:28:32] Using gulpfile /code/gulpfile.js
[03:28:32] Starting 'staging'...
[03:28:32] Starting 'clean'...
[03:28:32] Finished 'clean' after 38 ms
[03:28:32] Starting '<anonymous>'...
[03:28:32] Finished '<anonymous>' after 109 μs
[03:28:32] Starting 'vendorcss'...
[03:28:32] Starting 'vendorjs'...
[03:28:32] Starting 'css'...
[03:28:32] Starting 'js'...
[03:28:32] Starting 'html'...
[03:28:32] Starting 'images'...
[03:28:32] Starting 'fonts'...
[03:28:33] Finished 'css' after 733 ms
[03:28:33] Finished 'vendorcss' after 745 ms
[03:28:33] 'js' errored after 782 ms
[03:28:33] GulpUglifyError: unable to minify …
```
> Revert "Add required fields for meta attributes"

- docker/prod/worker/Dockerfile
Fixes Travis Error: https://travis-ci.org/github/Cloud-CV/EvalAI/builds/735260334#L4415
> [Docker] Fix worker dockerfile

- frontend/src/js/controllers/challengeCtrl.js
Add missing semi colon in `challengeCtrl.js` for the failing travis build --  https://travis-ci.org/github/Cloud-CV/EvalAI/builds/737578537#L2808
> Fix EvalAI travis build

- frontend/src/views/web/challenge/leaderboard.html
- frontend/src/views/web/landing.html
- frontend_v2/src/app/components/home/home.component.html
> update stats on homepage

- frontend/src/css/modules/base.scss
- frontend/src/css/modules/submission.scss
- frontend/src/views/web/challenge/submission.html
This PR fixes css inconsistency in submission meta attributes fields.
> [Frontend] Bugfixes in submission meta attributes css

- frontend/src/views/web/challenge/submission.html
Allow `.npz` input files in submissions.
> Accept npz file afor submission input

- scripts/deployment/deploy.sh
> Remove all the existing containers before deploying new containers

- scripts/monitoring/monitor_containers.py
- scripts/monitoring/run_monitor_containers.sh
This PR adds
```
0 */1 * * * /home/ubuntu/evalai/scripts/monitoring/run_monitor_containers.sh
```
> Deployment monitoring script

- apps/challenges/views.py
- apps/jobs/serializers.py
- frontend/src/js/controllers/challengeCtrl.js
- tests/unit/challenges/test_views.py
> Add submission meta fields in all_submission download

- scripts/deployment/deploy.sh
> Add missing "&&" in auto-deploy script

- frontend_v2/src/app/components/home/home.component.ts
- frontend_v2/src/app/components/nav/footer/footer.component.html
- frontend_v2/src/app/components/privacy-policy/privacy-policy.component.html
- frontend_v2/src/app/components/privacy-policy/privacy-policy.component.scss
- Limited popular challenges to be shown on homepage to 4.
- Replaced twitter Url
- Info msg shown to the user if they try to resubscribe.
- privacy policy page UI improved.
Privacy policy page:
> [Frontend_v2] Home Page Fixes

- .travis.yml
- docker/dev/django/Dockerfile
- docker/prod/django/Dockerfile
> Upgrade to python 3.7.5

- settings/prod.py
- settings/staging.py
> Add staging and prod domains to CORS

- .travis.yml
- docker/dev/django/Dockerfile
- docker/prod/django/Dockerfile
- requirements/prod.txt
This PR adds -
The issue mentioned in #3074 seems to be related to `python-autoreload`, refer [this](https://github.com/unbit/uwsgi/issues/1968).
> Upgrade to python 3.7.5 

- frontend/src/css/modules/submission.scss
- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/views/web/challenge/submission.html
> Add instructions for submission upload using cli on Submit page

- frontend/src/css/modules/leaderboard.scss
> Fix leaderboard baseline submission indent

- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/views/web/challenge/submission.html
> Add option to upload file using URL

- frontend/src/views/web/challenge-host-teams.html
> Add team ID in challenge host team page

- settings/prod.py
> Add https in CORS ORIGIN WHITELIST for prod

- apps/challenges/aws_utils.py
- requirements/common.txt
Revert `django_ses` package update. Refer this [issue](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/challenge-pk-725-production-workers/log-events/argoverse-3d-detection-competition-725-71837a72-afb0-4403-9cfc-bb3e80d733ab$252Fworker_argoverse-3d-detection-competition-725-71837a72-afb0-4403-9cfc-bb3e80d733ab$252F5cc4b34336d543eab49fde2d4f9e2b3a)
> Revert django ses update

- docs/source/index.rst
> Add docs for making submission public/private

- apps/challenges/views.py
> Add permissions to make PWC task leaderboard API to be only accessible by EvalAI staff user

- scripts/deployment/deploy.sh
This PR adds changes to auto deployment script for deploying using jumpbox instance.
> Setup auto deployment using jumpbox instance

- apps/accounts/migrations/0001_add_url_fields_in_profile_model.py
- apps/challenges/challenge_config_utils.py
- apps/challenges/challenge_notification_util.py
- apps/challenges/migrations/0052_add_error_bar.py
- apps/challenges/migrations/0053_added_is_registration_open_field.py
- apps/challenges/migrations/0054_add_banned_email_ids_field.py
- apps/challenges/migrations/0055_add_is_leaderboard_order_descending_in_phase_split_model.py
- apps/challenges/migrations/0056_add_leaderboard_decimal_precision_field_in_phase_split_model.py
- apps/challenges/migrations/0058_add_show_leaderboard_by_latest_submission_field_in_challenge_phase_split_model.py
- apps/challenges/migrations/0058_adding_environment_url_for_rl_challenges.py
- apps/challenges/migrations/0062_add_allowed_submission_file_types_field_in_phase_model.py
- apps/challenges/migrations/0063_add_slack_webhook_url_field_in_challenge_model.py
- apps/challenges/migrations/0064_add_is_restricted_to_select_one_submission_field_in_phase_model.py
- apps/challenges/migrations/0065_add_cluster_details_to_challenge_evaluation_cluster_model.py
- apps/challenges/migrations/0066_added_is_partial_submission_evaluation_enabled_field_in_phase_model.py
- apps/challenges/migrations/0067_add_submission_meta_attribute_field_to_challenge_phase.py
- apps/challenges/migrations/0068_change_test_annotation_to_be_null.py
- apps/jobs/migrations/0012_add_baseline_submission.py
- apps/jobs/migrations/0016_add_ignore_submission_boolean_field_in_submission_model.py
- apps/jobs/migrations/0017_add_submission_metadata_field_to_submission.py
- apps/participants/serializers.py
- apps/web/migrations/0009_added_subscribers_model.py
- apps/web/migrations/0010_add_verbose_name_plural_for_subscribers_model.py
- docs/source/conf.py
> Black formatting for codebase and migration files

- scripts/deployment/push.sh
> Revert "Remove SSL certificates from docker images"

- frontend_v2/src/app/components/publiclists/challengelist/challengelist.component.ts
Past challenges are being shown on the dashboard.
Fixes #3132
@RishabhJain2018 @Ram81
> [frontend_v2] Shows past challenges

- frontend/src/views/web/challenge/submission.html
This PR adds - 
[x] Check to disable visibility option to public/private when `leaderboard_public=False` for a challenge phase.
> [Frontend] Disable making submission public/private when leaderboard_public=False

- frontend/src/js/controllers/challengeCtrl.js
> BugFix: Disable submission visibility option when leaderboard_public=False

- scripts/workers/submission_worker.py
> Remove challenge start date less than current time check from submisson worker

- apps/challenges/aws_utils.py
- apps/challenges/views.py
> [code-upload-worker] Use host credentials if provided for code upload challenge cluster

- docker/dev/nodejs/Dockerfile
- docker/prod/nodejs/Dockerfile
Fix nodejs build issue. Refer [build log](https://travis-ci.org/github/Cloud-CV/EvalAI/builds/754890173#L2333)
> Fix nodejs docker container build issue

- apps/challenges/aws_utils.py
- apps/challenges/models.py
- settings/common.py
> Automate code upload cluster arn and subnet setup

- apps/challenges/aws_utils.py
Bug fix, AssumeRolePolicyDocument parameter is missing in EKS arn role creation.
> [BugFix]: Add AssumeRolePolicyDocument param in eks arn creation,

- apps/challenges/aws_utils.py
The PR fixes bug in boto3 API call for IAM policy attachment to a role.
> [BugFix] Incorrect function name IAM attach policy

- apps/challenges/aws_utils.py
- apps/challenges/utils.py
- scripts/workers/code_upload_worker_utils/deploy_calico.sh
> Remove calico and Pass host AWS keys to code upload worker

- apps/participants/utils.py
- apps/participants/views.py
- frontend/src/js/controllers/teamsCtrl.js
- frontend/tests/controllers-test/teamsCtrl.test.js
> Allow only team creator to update team details

- apps/challenges/serializers.py
- apps/challenges/urls.py
- apps/challenges/views.py
- tests/unit/challenges/test_serializers.py
- tests/unit/challenges/test_views.py
> Add API to get/update/delete challenge phase allowed email ids

- scripts/workers/code_upload_worker_utils/network_policies.yaml
Bug fix in substituting FQDN variable in yaml file
> [BugFix] FQDN variable name fix

- apps/challenges/aws_utils.py
Update kubernetes version of EKS cluster in code upload worker setup celery task
> [Code-Upload-Worker] Update kubernetes cluster version

- apps/challenges/aws_utils.py
> Revert "[Code-Upload-Worker] Update kubernetes cluster version"

- scripts/workers/code_upload_worker_utils/install_dependencies.sh
- scripts/workers/code_upload_worker_utils/network_policies.yaml
Hardcode `*.eval.ai` in cilium network policy to block all other outgoing traffic
> Hardcode FQDN in cilium network policy

- scripts/workers/code_upload_worker_utils/install_dependencies.sh
Remove cilium setup from fargate deployment
> Remove  cilium network policy

- frontend/src/views/web/landing.html
> Update challenge and users stats on homepage

- frontend/src/css/modules/submission.scss
- frontend/src/js/controllers/authCtrl.js
- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/views/web/challenge/submission.html
- frontend_v2/src/app/components/auth/login/login.component.ts
- frontend_v2/src/app/components/challenge/challengesubmit/challengesubmit.component.ts
- frontend_v2/src/app/services/auth.service.ts
- frontend_v2/src/styles/base.scss
> Fix #3249: Added JWT as Auth Token

- scripts/workers/code_upload_submission_worker.py
Currently, when a Kubernetes job for submission is deleted manually from the cluster the code upload submission worker keeps failing because it tries to delete the job. This PR handles the exception and reports it to sentry and clears the message from the submission queue to avoid redundant `delete_job` API calls.
> Handle job delete exception gracefully in code upload worker

- .github/CONTRIBUTING.md
Updated Contributing.md with necessary changes.
These are necessary lines taken from contributing.rst
> Updated contributing.md

- apps/challenges/views.py
Fixes #3128 
After changes preview:
> [Docs] Fix #3128: Add api documentation for download_all_submissions API

- apps/challenges/aws_utils.py
> [BugFix] Add EFS boto3 client for EFS APIs

- docker/prod/nodejs_v2/nginx_staging.conf
> Enable https endpoint for frontend v2 staging setup

- docker/prod/nodejs_v2/nginx_staging.conf
> Revert "Enable https endpoint for frontend v2 staging setup"

- docker/prod/nodejs_v2/Dockerfile
Copy ssl certs folder in frontend v2
> [BugFix] Copy ssl folder in frontend v2

- docker/prod/nodejs_v2/Dockerfile
Pass separate configuration for staging and production build for frontend v2
> Add separate staging and production frontend v2 build

- frontend_v2/src/environments/environment.staging.ts
Add staging https endpoint for frontend v2 backend endpoint
> Add staging https endpoint for frontend v2

- frontend_v2/src/environments/environment.staging.ts
- settings/staging.py
> Add new staging backend endpoint for frontend v2

- scripts/workers/code_upload_worker_utils/install_dependencies.sh
- scripts/workers/code_upload_worker_utils/network_policies.yaml
This PR -
-[x] Reverts to `matchName` in cilium network policy for code upload challenge
> Revert to cilium network policy deployment

- docker/prod/nodejs_v2/Dockerfile
Revert failing build for frontend v2. Logs are [here](https://travis-ci.com/github/Cloud-CV/EvalAI/builds/221383035#L6305)
> Revert frontend v2 config build

- docker/prod/nodejs_v2/Dockerfile
> Revert "Revert frontend v2 config build"

- docker/prod/nodejs_v2/Dockerfile
> Fix frontend v2 prod build issue

- docker-compose-production.yml
- docker-compose-staging.yml
> Comment nodejs_v2 for staging and production

- docker-compose-production.yml
- docker-compose-staging.yml
> Remove Frontend V2 docker container from staging and prod docker files

- frontend/src/js/controllers/profileCtrl.js
> Update refresh token on refresh in cache

- frontend_v2/src/app/components/challenge/challengesubmissions/challengesubmissions.component.html
- frontend_v2/src/app/components/challenge/challengesubmissions/challengesubmissions.component.ts
Fixes #3336 
@Ram81 @RishabhJain2018 , Please review this PR.
> [Frontend V2] Remove filter by team name from My submissions tab

- frontend_v2/src/app/components/challenge/challengeleaderboard/challengeleaderboard.component.html
- frontend_v2/src/app/components/challenge/challengephases/phasecard/phasecard.component.html
- frontend_v2/src/app/components/challenge/challengesubmissions/challengesubmissions.component.html
- frontend_v2/src/app/components/challenge/challengesubmissions/challengesubmissions.component.scss
- frontend_v2/src/app/components/challenge/challengesubmissions/challengesubmissions.component.ts
- frontend_v2/src/app/components/challenge/challengesubmit/challengesubmit.component.html
- frontend_v2/src/app/components/challenge/challengeviewallsubmissions/challengeviewallsubmissions.component.html
- frontend_v2/src/app/components/challenge/challengeviewallsubmissions/challengeviewallsubmissions.component.scss
- frontend_v2/src/app/components/utility/selectphase/selectphase.component.html
Fixes #3338 .
Fix font inconsistencies on my submission and all submissions page.
> Fix font inconsistencies

- .github/workflows/autoupdate.yaml
> Add Github workflow for auto updating can-be-merged PR's

- .github/workflows/autoupdate.yaml
> Change DRY_RUN to False in the autoupdate.yaml

- settings/staging.py
> Fix the media assets endpoint 

- .github/workflows/autoupdate.yaml
> Revert "Change schedule to every 10 mins for auto-updating PR's"

- apps/challenges/aws_utils.py
-[x] Add environment suffix in EKS nodegroup and cluster name when creating resource
> Add environment suffix in EKS cluster setup

- apps/challenges/aws_utils.py
Fixes bug in cluster name field introduced in #3398
> BugFix: Evaluation cluster name should not have spaces

- scripts/workers/code_upload_worker_utils/install_dependencies.sh
> Revert cilium deployment in code upload worker

- apps/challenges/utils.py
- apps/challenges/views.py
- frontend/src/js/controllers/challengeCtrl.js
> [Backend] Add submission meta attributes in download all submissions API

- frontend/src/views/web/challenge/challenge-page.html
- frontend/src/views/web/challenge/evaluation.html
> Add evaluation worker instructions and update approval instruction

- docker-compose-staging.yml
- docker/dev/nodejs_v2/Dockerfile
- docker/prod/nodejs_v2/Dockerfile
> Fix: Frontend V2 docker build

- docker/prod/nodejs_v2/nginx_staging.conf
- settings/staging.py
> Fix nginx API call redirection for frontend v2

- frontend_v2/src/app/components/challenge/challengesubmit/challengesubmit.component.html
**Issue:** 
**Fix:** Removed the unecessary submission card when challenge is not active
> [Minor Fix] remove submission card when challenge not active

- apps/jobs/views.py
> BugFix: Load json message from queue

- apps/jobs/urls.py
- apps/jobs/views.py
- scripts/workers/code_upload_submission_worker.py
> Add init container for submission started at update

- apps/challenges/aws_utils.py
> Enable circuit breaker for fargate tasks

- apps/challenges/aws_utils.py
> Revert "Enable circuit breaker for fargate tasks"

- frontend_v2/src/app/components/challenge/challengesubmit/challengesubmit.component.html
Almost all the font change was done in https://github.com/Cloud-CV/EvalAI/pull/3356, only one minor change in this PR.
If anywhere else, there is a need to change the font weight please let me know, I will update the PR accordingly.
> Change font and weight to Roboto 300

- frontend_v2/src/app/components/challenge/challengeevaluation/challengeevaluation.component.html
- frontend_v2/src/app/components/challenge/challengeevaluation/challengeevaluation.component.ts
- frontend_v2/src/app/components/challenge/challengesettings/challengesettings.component.html
- frontend_v2/src/app/components/challenge/challengesettings/challengesettings.component.ts
Added the edit evaluation script and upload file to the settings tab under the `Edit Challenge` card.
> Add edit evaluation script to settings tab

- frontend_v2/src/app/components/challenge-create/challenge-create.component.scss
- frontend_v2/src/app/components/challenge/challenge.component.html
- frontend_v2/src/app/components/challenge/challenge.component.scss
- frontend_v2/src/app/components/publiclists/publiclists.component.scss
- frontend_v2/src/styles/base.scss
Content is centered on challenge list and challenge page, same as v1.
> Conent center on challenge page

- apps/challenges/aws_utils.py
-[x] Fix usage of `is_static_dataset_code_upload` flag
> BugFix: Static code upload challenge flag usage

- scripts/workers/code_upload_submission_worker.py
> BugFix: Fix nvidia-device-plugin manifest path

- apps/jobs/views.py
- scripts/workers/code_upload_submission_worker.py
- scripts/workers/code_upload_worker_utils/make_submission.sh
Context: Static code upload challenge.
These changes are based on the testing of static code upload worker.
Deliverables:
@KhalidRmb 
cc: @Ram81
> Bug Fix: static code upload worker challenge integrations

- docker-compose-staging.yml
- docker/prod/nodejs_v2/nginx_staging.conf
> Migrate UI to Frontend V2

- frontend_v2/src/environments/environment.staging.ts
> [FrontendV2] Switch to staging backend endpoint

- docker/prod/nodejs_v2/nginx_staging.conf
> add statsd nginx config to frontend-v2

- scripts/deployment/deploy.sh
> [Deployment] Add statsd auto deployment

- scripts/workers/code_upload_submission_worker.py
Context: Code upload challenge worker.
Bug:
@KhalidRmb 
cc: @Ram81
> Update api_instacne for kubernetes token refresh

- docker/prod/nodejs_v2/nginx_staging.conf
> [Nginx] Increase upload limit for frontend v2

- frontend_v2/src/app/components/challenge/challengeleaderboard/challengeleaderboard.component.ts
Increases decimal precision to 20 and also displays the value received from backend.
> Increase decimal precision to 20 and display the previous precision

- frontend_v2/src/app/components/publiclists/teamlist/teamlist.component.html
- frontend_v2/src/app/components/publiclists/teamlist/teamlist.component.scss
Fixes buttons and card on teams page.
@Ram81 @Kajol-Kumari 
**Before**
**After**
> Fix buttons on team card

- docker-compose.yml
- frontend/src/css/modules/leaderboard.scss
- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/views/web/challenge/leaderboard.html
> [Frontend] Highlight clicked entry on leaderboard

- frontend_v2/src/app/components/publiclists/challengelist/challengecard/challengecard.component.ts
This PR removes the stars function from `challenge-card` component from `challenge-list` page.
This reduces the number of requests (5.5 sec to 1.5 sec though this number is based on the number of challenges I have on my local system)
> Remove stars from challenge-list page

- scripts/workers/code_upload_submission_worker.py
Context: Code upload worker.
This PR solves the following bugs
Detailed Explanation for point 3:
This scenario occurs when the job is created but the number of nodes available are fully utilized, so the job is created but the corresponding pod is in a pending state in which the container statuses does not exist. 
@KhalidRmb 
cc: @Ram81
> [Worker]: BugFix code upload worker for limited nodes

- scripts/workers/code_upload_submission_worker.py
Context: Code upload based challenges
-[x] Limit pod logs for stdout for code upload base challenges
@KhalidRmb 
cc: @Ram81
> Limit pod logs for stdout for code upload base challenges

- frontend/src/views/web/challenge/submission.html
> [Frontend] Fix instruction to make submission using CLI

- frontend/src/views/web/auth/login.html
- frontend/src/views/web/auth/signup.html
> [Frontend] Allow pasting password on login and signup page

- docker-compose-staging.yml
- docker/prod/nodejs_v2/nginx_staging.conf
- scripts/deployment/deploy.sh
> [FrontendV2] Deploy Frontend V2 on staging

- apps/challenges/views.py
> Fix schema json loading in leaderboard update API

- tests/unit/challenges/test_views.py
> [BugFix] Fix leaderboard schema update tests

- scripts/workers/submission_worker.py
> [Monitoring] Add is_remote flag in submission worker metrics

- monitoring/prometheus/rules.yml
> [BugFix] Worker down metric rule fix

- frontend_v2/src/app/components/challenge/challengeleaderboard/challengeleaderboard.component.html
- frontend_v2/src/app/components/challenge/challengeleaderboard/challengeleaderboard.component.scss
- frontend_v2/src/app/components/challenge/challengeleaderboard/challengeleaderboard.component.ts
> [FrontendV2] Highlight selected entry on leaderboard

- frontend_v2/src/app/components/challenge/challengesubmit/challengesubmit.component.html
- frontend_v2/src/app/components/challenge/challengesubmit/challengesubmit.component.scss
- frontend_v2/src/app/components/challenge/challengesubmit/challengesubmit.component.ts
- frontend_v2/src/app/components/utility/input/input.component.html
- frontend_v2/src/app/components/utility/input/input.component.ts
- frontend_v2/src/app/services/global.service.ts
- frontend_v2/src/styles/base.scss
> [FrontendV2] Add UI support for submission meta attributes

- frontend_v2/src/app/components/challenge/challengeleaderboard/challengeleaderboard.component.html
- frontend_v2/src/app/components/challenge/challengeleaderboard/challengeleaderboard.component.scss
- frontend_v2/src/app/components/challenge/challengeleaderboard/challengeleaderboard.component.ts
- scripts/workers/submission_worker.py
> [FrontendV2] Show leaderboard metric ordering and description tooltip

- frontend_v2/src/app/components/utility/selectphase/selectphase.component.ts
> [BugFix] Leaderboard phase split attribute access

- frontend_v2/src/app/components/challenge/challengeleaderboard/challengeleaderboard.component.ts
- frontend_v2/src/app/components/challenge/challengesubmit/challengesubmit.component.html
- frontend_v2/src/app/components/challenge/challengesubmit/challengesubmit.component.ts
> [BugFix] Meta attribute field visible check and leaderboard API call

- frontend_v2/src/app/app.component.html
- frontend_v2/src/app/app.component.ts
- frontend_v2/src/app/components/challenge/challenge.component.html
- frontend_v2/src/app/components/publiclists/publiclists.component.html
> [BugFix] Full width footer on All challenge page when user not logged in

- frontend_v2/src/app/components/challenge/challengesubmissions/challengesubmissions.component.html
- frontend_v2/src/app/components/challenge/challengesubmissions/challengesubmissions.component.scss
- frontend_v2/src/app/components/challenge/challengesubmissions/challengesubmissions.component.ts
> [FrontendV2] My submissions page improvements

- frontend_v2/src/app/components/challenge/challengesubmissions/challengesubmissions.component.html
- frontend_v2/src/app/components/challenge/challengesubmissions/challengesubmissions.component.scss
- frontend_v2/src/app/components/challenge/challengeviewallsubmissions/challengeviewallsubmissions.component.html
- frontend_v2/src/app/components/challenge/challengeviewallsubmissions/challengeviewallsubmissions.component.scss
- frontend_v2/src/app/components/utility/selectphase/selectphase.component.html
This PR - 
My submissions page:
All submissions page:
> [FrontendV2] My submissions and All submissions page Improvements

- frontend_v2/src/app/components/challenge/challengesubmissions/challengesubmissions.component.ts
- frontend_v2/src/app/components/utility/selectphase/selectphase.component.ts
- frontend_v2/src/app/services/challenge.service.ts
> [BugFix] Pagination and route redirection challenge page

- frontend_v2/src/app/components/challenge-create/challenge-create.component.html
- frontend_v2/src/app/components/challenge-create/challenge-create.component.scss
- frontend_v2/src/app/components/challenge/challengesubmit/challengesubmit.component.html
- frontend_v2/src/app/components/challenge/challengeviewallsubmissions/challengeviewallsubmissions.component.html
- frontend_v2/src/app/components/challenge/challengeviewallsubmissions/challengeviewallsubmissions.component.scss
> [BugFix] Improvements in FrontendV2

- apps/jobs/views.py
- frontend_v2/src/app/components/challenge/challengeparticipate/challengeparticipate.component.html
- frontend_v2/src/app/components/challenge/challengephases/phasecard/phasecard.component.html
- frontend_v2/src/app/components/challenge/challengesubmissions/challengesubmissions.component.html
- frontend_v2/src/app/components/challenge/challengesubmissions/challengesubmissions.component.ts
- frontend_v2/src/app/components/challenge/challengesubmit/challengesubmit.component.html
- frontend_v2/src/app/components/challenge/challengeviewallsubmissions/challengeviewallsubmissions.component.ts
- frontend_v2/src/app/components/publiclists/challengelist/challengelist.component.ts
- frontend_v2/src/app/components/publiclists/teamlist/teamcard/teamcard.component.html
- frontend_v2/src/app/components/publiclists/teamlist/teamcard/teamcard.component.ts
- frontend_v2/src/app/components/utility/input/input.component.html
- frontend_v2/src/app/components/utility/input/input.component.scss
- frontend_v2/src/app/components/utility/input/input.component.ts
- frontend_v2/src/app/components/utility/modal/modal.component.html
- frontend_v2/src/styles/base.scss
- requirements/dev.txt
> [FrontendV2] Improvements in challenge page

- frontend_v2/src/app/components/challenge/challenge.component.html
- frontend_v2/src/app/components/challenge/challenge.component.ts
- frontend_v2/src/app/components/challenge/challengesubmissions/challengesubmissions.component.html
- frontend_v2/src/app/components/challenge/challengesubmissions/challengesubmissions.component.ts
- frontend_v2/src/app/components/not-found/not-found.component.html
- frontend_v2/src/app/components/not-found/not-found.component.scss
- frontend_v2/src/app/components/utility/input/input.component.html
- frontend_v2/src/app/components/utility/input/input.component.ts
> [FrontendV2] Improve challenge page

- frontend_v2/src/app/components/challenge/challengesubmissions/challengesubmissions.component.html
- frontend_v2/src/app/components/challenge/challengesubmissions/challengesubmissions.component.ts
- frontend_v2/src/app/components/challenge/challengesubmit/challengesubmit.component.html
- frontend_v2/src/app/components/challenge/challengesubmit/challengesubmit.component.ts
- frontend_v2/src/app/components/not-found/not-found.component.html
- frontend_v2/src/app/components/utility/selectphase/selectphase.component.ts
> [FrontendV2] Bug fixes on challenge page

- frontend_v2/src/app/components/about/about.component.html
- frontend_v2/src/app/components/challenge/challengeparticipate/terms-and-conditions-modal/terms-and-conditions-modal.component.html
- frontend_v2/src/app/components/get-involved/get-involved.component.html
- frontend_v2/src/app/components/home/home.component.scss
- frontend_v2/src/app/components/our-team/our-team.component.ts
> Make font consistent across pages

- frontend_v2/src/app/components/auth/auth-routing.module.ts
> [FrontendV2] Fix password reset redirect URL

- frontend/src/views/web/privacy-policy.html
- frontend_v2/src/app/components/privacy-policy/privacy-policy.component.html
> Update privacy policy page

- docker/dev/worker_py3.8/Dockerfile
- docker/prod/worker_py3.8/Dockerfile
This PR -
FIxes [failing build](https://app.travis-ci.com/github/Cloud-CV/EvalAI/builds/249827262#L7926)
> [Worker] Update opencv version in worker py3.8

- apps/challenges/views.py
> [Logging] Add error logs in challenge validation and creation API

- docker/prod/nodejs_v2/nginx_production.conf
> [FrontendV2] Add production nginx config

- frontend_v2/src/app/components/challenge/challengeleaderboard/challengeleaderboard.component.ts
- frontend_v2/src/app/components/home/home.component.html
- frontend_v2/src/app/components/home/home.component.ts
> [BugFix] Add testimonials and fix default leaderboard metric arrow 

- frontend_v2/src/app/components/challenge/challengesubmissions/challengesubmissions.component.ts
> [BugFix] Fix edit submission modal popup in frontend v2

- settings/common.py
> [Backend] Increase pagination page size to 150

- docker/prod/nodejs_v2/nginx_production.conf
> [BugFix] Fix Frontend V2 redirection route to prod in nginx config

- frontend_v2/src/app/components/challenge/challengeleaderboard/challengeleaderboard.component.html
- frontend_v2/src/app/components/challenge/challengeleaderboard/challengeleaderboard.component.scss
> [FrontendV2] BugFix: Enable leaderboard horizontalscroll and show method name on leaderboard

- docker-compose-production.yml
- docker-compose-staging.yml
> [Backend] Add memcache container for throttling cache

- scripts/deployment/deploy.sh
> [Deployment] Add memcached server in auto deployment

- frontend_v2/src/app/components/challenge/challengesubmit/challengesubmit.component.html
> [BugFix]  Show challenge id and phase id on CLI submission instructions card

- requirements/worker.txt
> [Worker] Update numpy version in submission worker

- docker-compose-production.yml
> [Frontend] Revert to frontend v1

- docker/prod/nodejs/nginx_production.conf
- docker/prod/nodejs/nginx_staging.conf
> [Frontend] Add URL redirection for Frontend v2 backward compatibility

- docker-compose-staging.yml
> [Frontend] Switch to frontend v1 for staging deployment

- scripts/workers/code_upload_submission_worker.py
> [Code upload worker] Remove GPU constraint on job pod

- docs/source/github_based_challenge_setup.md
- docs/source/host_challenge.md
This PR fixes EvalAI starter links in the documentation.
> Fix EvalAI Starter links in Docs

- apps/challenges/aws_utils.py
> Revert: Add worker auto restart for static code upload challenge

- apps/challenges/serializers.py
- scripts/monitoring/auto_scale_workers.py
- scripts/monitoring/run_auto_scale_workers.sh
- tests/unit/challenges/test_views.py
- tests/unit/participants/test_views.py
This PR attempts to add a script to auto-scale workers in AWS to prevent unnecessary usage.
> Add worker auto scaling script

- frontend/src/js/controllers/challengeCtrl.js
- frontend/src/views/web/challenge/my-challenge-all-submission.html
- frontend/src/views/web/challenge/my-submission.html
- settings/common.py
> [Backend] Set pagination page size to 100

- apps/jobs/views.py
> Add checks to set submission visibility in large file upload API

- scripts/monitoring/auto_scale_workers.py
- scripts/monitoring/run_auto_scale_workers.sh
This PR adds the Prometheus API call to query prometheus server and fetch the required attributes for calculating queue length in the auto-scaling script.
> Use Prometheus to get queue length in auto-scaling

- scripts/monitoring/run_auto_scale_workers.sh
This PR fixes issues with the variables in auto scaling shell script.
> [Monitoring] Fix variables in auto-scaling shell script

- scripts/monitoring/auto_scale_workers.py
This PR changes the challenge queues for prod in the auto-scaling script.
> [Monitoring] Change challenge queues for prod in auto-scaling script

- apps/challenges/models.py
This PR increases default number of CPU cores and memory for the workers.
> Increase CPU cores and memory for workers

- scripts/monitoring/auto_scale_workers.py
This PR adds some debugging statements and changes to apply auto-scaling to all workers/challenges on prod.
> Apply auto scaling to all workers on prod

- scripts/monitoring/auto_scale_workers.py
This PR adds auto-scaling for unapproved challenges and excludes certain challenges from check on prod.
> Add auto-scaling for unapproved challenges

- scripts/workers/submission_worker.py
Add flush method to handle flushing of the file handles in MultiOut.
> Add flush method to MultiOut

- apps/challenges/views.py
This PR checks for the end date in manager worker API in order to allow only delete action for the past challenges.
> Check actions for past challenges in manage worker

- scripts/monitoring/auto_scale_workers.py
This PR modifies the auto-scaling script in order to only allow downscaling for the past challenge workers.
> Allow only downscaling for past challenge workers

- apps/challenges/views.py
This PR fixes the datetime check in manage worker.
> Fix datetime check in manage worker

- apps/challenges/aws_utils.py
> [BugFix] Add num_of_tasks in update service task definition

- scripts/monitoring/auto_scale_workers.py
This PR fixes the auto-scaling script which was failing due to a datetime related error.
> Fix auto scaling script

- bower.json
IMPORTANT NOTES (please read, then delete):
* The PR title should start with "Fix #bugnum: " (if applicable), followed by a clear one-line present-tense summary of the changes introduced in the PR. For example: "Fix #bugnum: Introduce the first version of the collection editor.".
* Please make sure to mention "#bugnum" somewhere in the description of the PR. This enables GitHub to link the PR to the corresponding bug.
Please also make sure to follow the [style rules](https://github.com/Cloud-CV/EvalAI/blob/master/.github/CONTRIBUTING.md#style-rules).
> Fixed #3834: fixed a version of the trix package

- frontend/src/views/web/challenge/manage.html
This PR fixes the resources mentioned in the note on manage tab according to the latest defaults.
> Fix resources mentioned in note on manage tab

- docker-compose-production.yml
- docker-compose-staging.yml
- docker-compose.yml
- docker/dev/worker_py3.8/Dockerfile
- docker/prod/worker_py3.8/Dockerfile
This PR adds Python 3.8 worker, reverting the change made in #3733.
> Add Python 3.8 worker

- scripts/monitoring/run_auto_stop_workers.sh
This PR renames the auto stop shell script with the name according to the new python script.
> Rename auto stop workers script

- apps/challenges/challenge_config_utils.py
- apps/challenges/views.py
This PR adds checks for ID validation in leaderboard, challenge phases and dataset splits.
> Improve validate challenge config API

- scripts/monitoring/auto_scale_eks_nodes.py
This PR fixes the EKS auto scaling script.
> Fix EKS auto scaling script

- scripts/workers/code_upload_submission_worker.py
- scripts/workers/statsd_utils.py
- scripts/workers/submission_worker.py
This PR fixes the failing import of `increment_and_push_metrics_to_statsd` in code-upload submission worker.
> Fix statsd increment import in code upload worker

- apps/challenges/task_definitions.py
This PR adds missing statsd environment variables to code upload submission worker task definition.
> Add StatsD env variable to code upload task definition

- docs/source/evaluation_scripts.md
- docs/source/host_challenge.md
This PR adds docs for static code-upload based challenges.
> Add docs for static code-upload challenges

- apps/challenges/aws_utils.py
This PR upgrades the EKS Kubernetes server version
> Upgrade EKS Kubernetes server version to 1.22

- scripts/tools/cleanup_docker_images.sh
This PR adds script to clean up docker images on staging and production.
> Add script to clean up docker images

- apps/jobs/serializers.py
This PR fixes the issue with submission serializer which is currently failing as `context` is not defined.
> Fix representation in submission serializer

- scripts/workers/code_upload_submission_worker.py
This PR removes the terminated condition in the code upload submission worker to upload the logs if whenever the container is terminated for any reason.
> Fix code upload worker environment logging

- .github/workflows/autoupdate.yaml
This PR upgrades the auto-update Ubuntu version as it is deprecated.
> [Deployment] Upgrade environment in autoupdate action

- frontend/src/js/controllers/challengeListCtrl.js
This PR removes the print statements from the challengeListCtrl.
> Remove print statements from challengeListCtrl

- docker-compose-production.yml
- docker-compose-staging.yml
- scripts/deployment/deploy.sh
This PR removed frontend v2 from deployment on staging and production.
> [Deployment] Remove frontend v2 from deployment

- apps/jobs/admin.py
- apps/jobs/utils.py
- apps/jobs/views.py
This PR fixes the prometheus metrics on admin actions. Re-runs and cancels update the number of processed submissions to make sure the prometheus metrics are accurate.
> [Monitoring] Fix Prometheus metrics on admin actions

- apps/jobs/admin.py
- apps/jobs/utils.py
- apps/jobs/views.py
> Revert "[Monitoring] Fix Prometheus metrics on admin actions"

- frontend/src/js/route-config/route-config.js
fix #3894 
For non authorised users
For challenge host user
> [BugFix] Fix manage and all submissions page visibility

- apps/challenges/views.py
This PR is for testing get all challenges endpoint on staging.
> Add try except to challenge views

- apps/challenges/views.py
This PR removes try-except statements from get all challenges endpoint which were added for debugging.
> [BugFix] Remove try except from get challenges API

- apps/challenges/views.py
- docker-compose.yml
This PR temporarily adds try and except to the view that fetches AWS credentials.
> [BugFix] Add try except to AWS credentials view

- apps/challenges/views.py
- docker-compose.yml
> Revert "[BugFix] Add try except to AWS credentials view"

- apps/challenges/views.py
> Revert "[BugFix] Add try except to view for AWS credentials"

- frontend/src/views/web/challenge/my-challenge-all-submission.html
This PR fixes the all submissions frontend code.
> [BugFix] Fix all submissions frontend

- frontend/src/js/controllers/analyticsCtrl.js
This PR fixes the problem with download all participants where special characters prevent entire CSV from getting downloaded.
> [BugFix] Fix download all participants with spl chars

- scripts/workers/submission_worker.py
This PR fixes the issue with disable logs in the submission worker.
> Fix issue with disable logs in submission worker

- scripts/monitoring/auto_scale_eks_nodes.py
This PR fixes the flake8 issue with EKS auto scaling script.
> [BugFix] Fix flake8 issue with auto scaling EKS

- apps/challenges/challenge_config_utils.py
- apps/challenges/utils.py
- apps/challenges/views.py
Fixed function check_tags and check_domain not being called in validation process, return Response from utils changed to a variable instead as it doesn't work outside the .views
> [BugFix] Fix validation for tags and domains

- apps/accounts/serializers.py
Removed affiliation requirement  for profile update
> [Frontend] Remove affiliation requirement for profile update

- apps/jobs/views.py
This PR allows admin to use`get_submissions_for_challenge` API.
> [Backend] Allow admin to get submissions by challenge

- apps/jobs/views.py
This PR allows admins to update submissions.
> [Backend] Allow admins to update submissions

- scripts/monitoring/auto_scale_eks_nodes.py
This PR allows custom EKS auto scaling desired nodegroup size for potential parallel evaluations.
> [Monitoring] Allow custom size EKS auto scale

- docker/prod/nodejs/Dockerfile
Added loglevel to see the npm install information
> [Deployment] Add log level for npm installation

- docker/prod/nodejs/Dockerfile
> Revert "[Deployment] Add log level for npm installation"

- frontend/src/js/route-config/route-config.js
- frontend/src/views/web/profile/profile.html
Fix change password tab not being open
> [BugFix] Fix change password tab not working

- scripts/monitoring/auto_scale_workers.py
This PR excludes CVPR 2023 challenge from auto scaling script.
> [Monitoring] Exclude CVPR 2023 from auto scaling

- scripts/monitoring/auto_scale_eks_nodes.py
This PR allows multi-step EKS auto scaling.
> [Monitoring] Allow multi-step EKS auto scaling

- apps/challenges/aws_utils.py
This PR fixes the issue with fetching logs from several log streams, the problem is that boto3 returns a next token to get further logs which is not being used.
> [BugFix] Add recursive fetching of logs in worker

- apps/jobs/views.py
This PR allows updating submissions to queued status during update submission PATCH request.
> [BugFix] Add queued status for submission update

- scripts/monitoring/auto_scale_eks_nodes.py
This PR fixes the EKS auto scaling script and allows scaling up to a maximum size set in the auto scaling details JSON.
This won't scale down things until all pending submissions are finished, even if there are extra nodes in the nodegroups.
> [Monitoring] Update auto scale EKS to vary with size up to max

- apps/challenges/aws_utils.py
This PR fixes worker instance type fetching on EC2 setup in AWS utils.
> [BugFix] Fix worker instance type on EC2 setup

- apps/challenges/aws_utils.py
- scripts/deployment/deploy_ec2_worker.sh
This PR fixes missing AWS account ID export in EC2 setup.
> [BugFix] Fix missing account ID in EC2 setup

- scripts/deployment/deploy_ec2_worker.sh
This PR fixes EC2 deployment script for EC2 setup.
> [BugFix] Fix EC2 deployment script

- apps/challenges/aws_utils.py
- scripts/deployment/deploy_ec2_worker.sh
> Fix: #4096 [Scripts] Add crontab and comments to deploy ec2 worker script

- apps/challenges/aws_utils.py
- apps/challenges/urls.py
- apps/challenges/views.py
This PR adds an API to get EC2 instance details.
> [Backend] Add API to get EC2 instance details

- scripts/deployment/deploy_ec2_worker.sh
This PR fixes the crontab setup in the EC2 script.
> [BugFix] Fix crontab setup in EC2 script

- apps/challenges/aws_utils.py
- scripts/monitoring/auto_scale_ec2_workers.py
- scripts/monitoring/evalai_interface.py
This PR fixes a few bugs with EC2 setup, APIs and auto scaling scripts.
> [BugFix] Fix bugs with EC2

- scripts/monitoring/auto_scale_ec2_workers.py
This PR fixes existing flake8 issues.
> [BugFix] Fix flake8 issues

- scripts/deployment/deploy_ec2_worker.sh
Fix CUSTOM_WORKER_IMAGE not being checked and being used
> [Deployment] Fix custom worker image in EC2 deployment

- apps/challenges/urls.py
- apps/challenges/views.py
- tests/unit/challenges/test_views.py
Add challenge phase split filter to get all leaderboard method
> [Backend] Add challenge phase split filter to get all leaderboard method

- settings/common.py
> Revert "[Debug] Add debug logging to Django loggers"

- apps/challenges/urls.py
- apps/challenges/views.py
- tests/unit/challenges/test_views.py
Add a api to allow staff to update challenge approval state
> [Backend] Add update challenge approval API

- apps/jobs/utils.py
- apps/jobs/views.py
> [BugFix] Allow staff to access leaderboard data

- frontend/src/css/modules/challenge.scss
- frontend/src/js/controllers/challengeListCtrl.js
- frontend/src/js/controllers/hostedChallengeCtrl.js
- frontend/src/views/web/challenge-list.html
- frontend/src/views/web/hosted-challenges.html
> Revert "[Frontend] Add search and filter for challenges"

- apps/challenges/challenge_config_utils.py
Fixes error message for prize amount invalid and rank invalid
> [BugFix] Fix error message for prizes and sponsors

- apps/challenges/aws_utils.py
- apps/challenges/models.py
- apps/challenges/urls.py
- apps/challenges/views.py
This PR improves the existing EC2 instance APIs
> [Backend] Improve EC2 instance APIs

- apps/jobs/views.py
> Revert "[BugFix] Fix duplicate leaderboard data entry creation on resume"

- apps/challenges/challenge_config_utils.py
- apps/challenges/views.py
> Revert "[Backend] Add or delete challenge phases and splits"

- scripts/monitoring/auto_scale_ec2_workers.py
- scripts/monitoring/auto_scale_eks_nodes.py
- scripts/monitoring/auto_scale_workers.py
This PR adds try except blocks to auto scaling scripts.
> [BugFix] Add try except to auto scaling scripts

- apps/challenges/aws_utils.py
Need this as AWS does not support 1.22 anymore.
> [Worker] Update kubernetes version

- scripts/deployment/delete_old_submissions.py
- scripts/deployment/deploy_ec2_worker.sh
This PR adds clearing of submissions for EC2 instances on reboot. This helps reduce storage requirements and will save costs on the workers staying up because of stuck evaluations.
> [Deployment] Add submission clearing for EC2

- scripts/workers/code_upload_worker_utils/install_dependencies.sh
This PR moves to FluentBit insights, as FluentD Compatible insights are not reliable.
> [BugFix] Switch to FluentBit Container Insights

- scripts/workers/code_upload_worker_utils/install_dependencies.sh
This PR updates AWS drivers as the old ones are throwing errors on EFS mounting.
> [Deployment] Update AWS driver versions

- docker/dev/code-upload-worker/Dockerfile
- docker/prod/code-upload-worker/Dockerfile
- docker/prod/django/Dockerfile
> Revert "[Backend] Move to Python 3.8"

- docker/prod/django/Dockerfile
This reverts commit 9bb93896747def60bb4ea10fdbf82f75cf93a7e6.
IMPORTANT NOTES (please read, then delete):
* The PR title should start with "Fix #bugnum: " (if applicable), followed by a clear one-line present-tense summary of the changes introduced in the PR. For example: "Fix #bugnum: Introduce the first version of the collection editor.".
* Please make sure to mention "#bugnum" somewhere in the description of the PR. This enables GitHub to link the PR to the corresponding bug.
Please also make sure to follow the [style rules](https://github.com/Cloud-CV/EvalAI/blob/master/.github/CONTRIBUTING.md#style-rules).
> Revert "[BugFix] Turn off pip Progress bar (#4241)"

- apps/challenges/views.py
This PR adds try except to AWS credentials API in order to have better error logging.
While this PR is temporary, we can have more verbose logs in general to help participants pinpoint the issue easily.
> [BugFix] Add try-except to AWS credentials API

- apps/challenges/views.py
> Revert "[BugFix] Add try-except to AWS credentials API"

- frontend/src/views/web/landing.html
- frontend_v2/src/app/components/home/home.component.html
This PR updates -
1. Hosted Challenges
2. Number of Users on EvalAI
3. Number of Submissions
4. Number of Organizations using EvalAI
> [Frontend] Update stats on home page

- frontend/src/views/web/landing.html
- frontend_v2/src/app/components/home/home.component.html
This PR -
- Updates the number of submissions stat from 350K to 430K on the landing page.
> Frontend: Update number of submissions stat on the landing page

- apps/challenges/urls.py
- apps/challenges/views.py
> [Backend] Add submissions metrics by PK

- frontend/src/views/web/challenge/manage.html
This PR updates the worker note regarding resources based on our current way of doing things.
> [Frontend] Update worker note regarding resources

- README.md
This PR:
- Updates README.md with Slack Invite Link
> Update README.md with Slack Invite Link

- .coveralls.yml
This PR -
- Coveralls: Update token in .coveralls.yml
> Coveralls: Update token in .coveralls.yml

- README.md
This PR -
- Removes Code Climate Badge
- Adds Commit Activity Badge
> ReadME: Update README.md with commit activity badge

- .travis.yml
This PR fixes: [Travis Build](https://app.travis-ci.com/github/Cloud-CV/EvalAI/jobs/631783000?serverType=git)
> Remove deploy from a separate job and add it to after_success

- .travis.yml
> Revert "Remove deploy from a separate job and add it to after_success"

- .travis.yml
- docker-compose.yml
This PR:
- Adds worker & statsd container in the build
> Adds worker & statsd container in the build

- scripts/deployment/push.sh
> Revert "Export environment variables to fix staging build"

- frontend/src/views/web/landing.html
This PR:
- Updates stats on homepage
> Frontend: Update stats on homepage

- .travis.yml
> TravisCI: Merge Build and Test Stages in TravisCI

- evalai/urls.py
This PR increases the pylint score of `evalai/urls.py`
> Increased pylint score by fixing character length 

- .github/workflows/autoupdate.yaml
This PR:
- Updates the Ubuntu Version to 22.04
> Update ubuntu version

- frontend/src/views/web/challenge/submission.html
This PR is about modifying challenge submission part.
Added time limit to "Today's Remaining Submission Column - Resets at 12:00 AM UTC".
> Modified Challenge submissions part

- frontend/src/css/modules/landing.scss
- frontend/src/views/web/landing.html
Modified position of opencv organization on the landing page.
> Modified logos of partner organizations on the landing page

- scripts/workers/code_upload_submission_worker.py
This PR:
- Fixes the relative imports in the code upload worker
> Fix relative imports in code upload worker

- frontend/src/views/web/challenge-list.html
Modified the challenge card  by setting 2 tags only and removing GMT timezone from the card.
> Modified the challenge card 

- frontend/src/js/controllers/profileCtrl.js
- frontend/tests/controllers-test/profileCtrl.test.js
> Revert "Added an error message on profile updateChanged Error Message"

- frontend/src/css/modules/challenge.scss
- frontend/src/views/web/hosted-challenges.html
Modified challenge card of My Hosted Challenges Page-
1 Removed GMT Timezone
2 Increase height of the challenge card
3 Limit the tags to 2
> Modified challenge card of My Hosted Challenges Page

- docker-compose-production.yml
- docker-compose-staging.yml
This PR:
- Fixes the path for remote worker container
> Remote Worker Path fix

- frontend/tests/controllers-test/permissionCtrl.test.js
**Fixes:** #4679
The coverage for permissionCtrl.js is now 100%
> Added Test for permissionCtrl.js

- frontend/tests/controllers-test/authCtrl.test.js
**Fixes:** #4678
The Coverage for authCtrl.js is now 98.62%
> Added Test for AuthCtrl.js

- tests/unit/worker/test_code_upload_submission_worker.py
- tests/unit/worker/test_remote_submission_worker.py
- tests/unit/worker/test_submission_worker.py
**Fixes:** #4676
**Previous Coverage:**
**Coverage After This Pull Request:**
> Added Test for Worker App 

- tests/unit/web/test_apps.py
- tests/unit/web/test_models.py
- tests/unit/web/test_views.py
> Added Test for Web App

- frontend/tests/controllers-test/analyticsCtrl.test.js
**Fixes:** #4725
The coverage for analyticsCtrl.js is 97.59%
> Added test for analyticsCtrl.js

- tests/unit/jobs/test_admin.py
- tests/unit/jobs/test_sender.py
- tests/unit/jobs/test_serializer.py
- tests/unit/jobs/test_tasks.py
- tests/unit/jobs/test_utils.py
> Added Test for Job App

- frontend/tests/controllers-test/teamsCtrl.test.js
> Revert "Added test for teamsCtrl.js"

- .coveralls.yml
- README.md
Remove Coveralls configuration and update README to reflect changes
> Remove Coveralls configuration and update README to reflect changes

- README.md
Update README to enhance coverage badges and clarify reporting for backend and frontend
> Update README to enhance coverage badges and clarify reporting for backend and frontend
